coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "crates/fhir/src/r4/"
  - "crates/fhir/src/r4b/"
  - "crates/fhir/src/r5/"
  - "crates/fhir/src/r6/"
  - "crates/hfs/src/main.rs"
  - "crates/hts/src/main.rs"