// @generated by fhir-valueset-gen
// DO NOT EDIT MANUALLY

//! ContractContentDerivative
//!
//! This is an example set of Content Derivative type codes, which represent the minimal content derived from the basal information source at a specific stage in its lifecycle, which is sufficient to manage that source information, for example, in a repository, registry, processes and workflows, for making access control decisions, and providing query responses.

use super::super::super::{CodeableConcept, Coding};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum ContractContentDerivative {
    Registration,
    Retrieval,
    Statement,
    Shareable,
}

impl ContractContentDerivative {
    pub const URL: &'static str = "http://hl7.org/fhir/contract-content-derivative";
    pub const VERSION: &'static str = "4.3.0";
    pub const STATUS: &'static str = "draft";
    pub const CONTENT: &'static str = "complete";
    pub const EXPERIMENTAL: bool = true;
    pub const CASE_SENSITIVE: bool = true;
    pub const HAS_CONCEPTS: bool = true;

    pub fn as_code(self) -> &'static str {
        match self {
            Self::Registration => "registration",
            Self::Retrieval => "retrieval",
            Self::Statement => "statement",
            Self::Shareable => "shareable",
        }
    }

    pub fn try_from_code(code: &str) -> Option<Self> {
        Some(match code {
            "registration" => Self::Registration,
            "retrieval" => Self::Retrieval,
            "statement" => Self::Statement,
            "shareable" => Self::Shareable,
            _ => return None,
        })
    }

    pub fn display(self) -> Option<&'static str> {
        match self {
            Self::Registration => Some("Content Registration"),
            Self::Retrieval => Some("Content Retrieval"),
            Self::Statement => Some("Content Statement"),
            Self::Shareable => Some("Shareable Content"),
        }
    }

    pub fn definition(self) -> Option<&'static str> {
        match self {
            Self::Registration => Some(
                "Content derivative that conveys sufficient information needed to register the source basal content from which it is derived.  This derivative content may be used to register the basal content as it changes status in its lifecycle.  For example, content registration may occur when the basal content is created, updated, inactive, or deleted.",
            ),
            Self::Retrieval => Some(
                "A content derivative that conveys sufficient information to locate and retrieve the content.",
            ),
            Self::Statement => Some(
                "Content derivative that has less than full fidelity to the basal information source from which it was \'transcribed\'. It provides recipients with the full content representation they may require for compliance purposes, and typically include a reference to or an attached unstructured representation for recipients needing an exact copy of the legal agreement.",
            ),
            Self::Shareable => Some(
                "A Content Derivative that conveys sufficient information to determine the authorized entities with which the content may be shared.",
            ),
        }
    }

    pub fn parent_code(self) -> Option<&'static str> {
        match self {
            Self::Registration => None,
            Self::Retrieval => None,
            Self::Statement => None,
            Self::Shareable => None,
        }
    }

    pub fn level(self) -> u16 {
        match self {
            Self::Registration => 0,
            Self::Retrieval => 0,
            Self::Statement => 0,
            Self::Shareable => 0,
        }
    }
    pub fn to_coding(self) -> Coding {
        Coding {
            id: None,
            extension: None,
            system: Some(Self::URL.to_string().into()),
            version: Some(Self::VERSION.to_string().into()),
            code: Some(self.as_code().to_string().into()),
            display: self.display().map(|d| d.to_string().into()),
            user_selected: None,
        }
    }

    pub fn to_codeable_concept(self) -> CodeableConcept {
        let coding = self.to_coding();
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: self.display().map(|d| d.to_string().into()),
        }
    }

    pub fn matches_coding(self, coding: &Coding) -> bool {
        let system = coding.system.as_ref().and_then(|e| e.value.as_deref());
        let code = coding.code.as_ref().and_then(|e| e.value.as_deref());
        system == Some(Self::URL) && code == Some(self.as_code())
    }

    pub fn matches_codeable_concept(self, cc: &CodeableConcept) -> bool {
        cc.coding
            .as_ref()
            .map(|v| {
                v.iter().any(|c| {
                    let system = c.system.as_ref().and_then(|e| e.value.as_deref());
                    let code = c.code.as_ref().and_then(|e| e.value.as_deref());
                    system == Some(Self::URL) && code == Some(self.as_code())
                })
            })
            .unwrap_or(false)
    }
}
