// @generated by fhir-valueset-gen
// DO NOT EDIT MANUALLY

//! PediatricUse
//!
//! Suitability for age groups, in particular children.

use super::super::super::{CodeableConcept, Coding};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum PediatricUse {
    InUtero,
    PretermNewborn,
    TermNewborn,
    Infants,
    Children,
    Adolescents,
    Adults,
    Elderly,
    Neonate,
    PediatricPopulation,
    All,
    Prepubertal,
    AdultsAndElderly,
    PubertalAndPostpubertal,
}

impl PediatricUse {
    pub const URL: &'static str = "http://hl7.org/fhir/medicinal-product-pediatric-use";
    pub const VERSION: &'static str = "4.3.0";
    pub const STATUS: &'static str = "draft";
    pub const CONTENT: &'static str = "complete";
    pub const EXPERIMENTAL: bool = false;
    pub const CASE_SENSITIVE: bool = true;
    pub const HAS_CONCEPTS: bool = true;

    pub fn as_code(self) -> &'static str {
        match self {
            Self::InUtero => "InUtero",
            Self::PretermNewborn => "PretermNewborn",
            Self::TermNewborn => "TermNewborn",
            Self::Infants => "Infants",
            Self::Children => "Children",
            Self::Adolescents => "Adolescents",
            Self::Adults => "Adults",
            Self::Elderly => "Elderly",
            Self::Neonate => "Neonate",
            Self::PediatricPopulation => "PediatricPopulation",
            Self::All => "All",
            Self::Prepubertal => "Prepubertal",
            Self::AdultsAndElderly => "AdultsAndElderly",
            Self::PubertalAndPostpubertal => "PubertalAndPostpubertal",
        }
    }

    pub fn try_from_code(code: &str) -> Option<Self> {
        Some(match code {
            "InUtero" => Self::InUtero,
            "PretermNewborn" => Self::PretermNewborn,
            "TermNewborn" => Self::TermNewborn,
            "Infants" => Self::Infants,
            "Children" => Self::Children,
            "Adolescents" => Self::Adolescents,
            "Adults" => Self::Adults,
            "Elderly" => Self::Elderly,
            "Neonate" => Self::Neonate,
            "PediatricPopulation" => Self::PediatricPopulation,
            "All" => Self::All,
            "Prepubertal" => Self::Prepubertal,
            "AdultsAndElderly" => Self::AdultsAndElderly,
            "PubertalAndPostpubertal" => Self::PubertalAndPostpubertal,
            _ => return None,
        })
    }

    pub fn display(self) -> Option<&'static str> {
        match self {
            Self::InUtero => Some("In utero"),
            Self::PretermNewborn => Some("Preterm newborn infants (0 \u{2013} 27 days)"),
            Self::TermNewborn => Some("Term newborn infants (0 \u{2013} 27 days)"),
            Self::Infants => Some("Infants and toddlers (28 days \u{2013} 23 months)"),
            Self::Children => Some("Children (2 to < 12 years)"),
            Self::Adolescents => Some("Adolescents (12 to < 18 years)"),
            Self::Adults => Some("Adults (18 to < 65 years)"),
            Self::Elderly => Some("Elderly (\u{2265} 65 years)"),
            Self::Neonate => Some("Neonate"),
            Self::PediatricPopulation => Some("Pediatric Population (< 18 years)"),
            Self::All => Some("All"),
            Self::Prepubertal => Some("Prepubertal children (2 years to onset of puberty)"),
            Self::AdultsAndElderly => Some("Adult and elderly population (> 18 years)"),
            Self::PubertalAndPostpubertal => {
                Some("Pubertal and postpubertal adolescents (onset of puberty to < 18 years)")
            }
        }
    }

    pub fn definition(self) -> Option<&'static str> {
        match self {
            Self::InUtero => Some("In utero"),
            Self::PretermNewborn => Some("Preterm newborn infants (0 \u{2013} 27 days)"),
            Self::TermNewborn => Some("Term newborn infants (0 \u{2013} 27 days)"),
            Self::Infants => Some("Infants and toddlers (28 days \u{2013} 23 months)"),
            Self::Children => Some("Children (2 to < 12 years)"),
            Self::Adolescents => Some("Adolescents (12 to < 18 years)"),
            Self::Adults => Some("Adults (18 to < 65 years)"),
            Self::Elderly => Some("Elderly (\u{2265} 65 years)"),
            Self::Neonate => Some("Neonate"),
            Self::PediatricPopulation => Some("Pediatric Population (< 18 years)"),
            Self::All => Some("All"),
            Self::Prepubertal => Some("Prepubertal children (2 years to onset of puberty)"),
            Self::AdultsAndElderly => Some("Adult and elderly population (> 18 years)"),
            Self::PubertalAndPostpubertal => {
                Some("Pubertal and postpubertal adolescents (onset of puberty to < 18 years)")
            }
        }
    }

    pub fn parent_code(self) -> Option<&'static str> {
        match self {
            Self::InUtero => None,
            Self::PretermNewborn => None,
            Self::TermNewborn => None,
            Self::Infants => None,
            Self::Children => None,
            Self::Adolescents => None,
            Self::Adults => None,
            Self::Elderly => None,
            Self::Neonate => None,
            Self::PediatricPopulation => None,
            Self::All => None,
            Self::Prepubertal => None,
            Self::AdultsAndElderly => None,
            Self::PubertalAndPostpubertal => None,
        }
    }

    pub fn level(self) -> u16 {
        match self {
            Self::InUtero => 0,
            Self::PretermNewborn => 0,
            Self::TermNewborn => 0,
            Self::Infants => 0,
            Self::Children => 0,
            Self::Adolescents => 0,
            Self::Adults => 0,
            Self::Elderly => 0,
            Self::Neonate => 0,
            Self::PediatricPopulation => 0,
            Self::All => 0,
            Self::Prepubertal => 0,
            Self::AdultsAndElderly => 0,
            Self::PubertalAndPostpubertal => 0,
        }
    }
    pub fn to_coding(self) -> Coding {
        Coding {
            id: None,
            extension: None,
            system: Some(Self::URL.to_string().into()),
            version: Some(Self::VERSION.to_string().into()),
            code: Some(self.as_code().to_string().into()),
            display: self.display().map(|d| d.to_string().into()),
            user_selected: None,
        }
    }

    pub fn to_codeable_concept(self) -> CodeableConcept {
        let coding = self.to_coding();
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: self.display().map(|d| d.to_string().into()),
        }
    }

    pub fn matches_coding(self, coding: &Coding) -> bool {
        let system = coding.system.as_ref().and_then(|e| e.value.as_deref());
        let code = coding.code.as_ref().and_then(|e| e.value.as_deref());
        system == Some(Self::URL) && code == Some(self.as_code())
    }

    pub fn matches_codeable_concept(self, cc: &CodeableConcept) -> bool {
        cc.coding
            .as_ref()
            .map(|v| {
                v.iter().any(|c| {
                    let system = c.system.as_ref().and_then(|e| e.value.as_deref());
                    let code = c.code.as_ref().and_then(|e| e.value.as_deref());
                    system == Some(Self::URL) && code == Some(self.as_code())
                })
            })
            .unwrap_or(false)
    }
}
