// AUTO-GENERATED by atrius-fhir-generator (R4 CompartmentDefinition)
use crate::r4::*;

/// FHIR CompartmentDefinition type
///
/// A compartment definition that defines how resources are accessed on a server.
///
/// ## Type: Resource type
/// Base type: http://hl7.org/fhir/StructureDefinition/DomainResource
///
/// ## Status: draft
/// FHIR Version: 4.0.1
///
/// See: [CompartmentDefinition](http://hl7.org/fhir/StructureDefinition/CompartmentDefinition)
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(
    summary_fields = "id,meta,implicit_rules,url,version,name,status,experimental,date,publisher,contact,use_context,code,search,resource"
)]
pub struct CompartmentDefinition {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    ///
    /// ## Implementation Notes
    /// The only time that a resource does not have an id is when it is being
    /// submitted to the server using a create operation.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    pub id: Option<String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub meta: Option<Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content. Often,
    /// this is a reference to an implementation guide that defines the special rules
    /// along with other profiles etc.
    ///
    /// ## Implementation Notes
    /// Asserting this rule set restricts the content to be only understood by a
    /// limited set of trading partners. This inherently limits the usefulness of the
    /// data in the long term. However, the existing health eco-system is highly
    /// fractured, and not yet ready to define, collect, and exchange data in a
    /// generally computable sense. Wherever possible, implementers and/or
    /// specification writers should avoid using this element. Often, when used, the
    /// URL is a reference to an implementation guide that defines these special
    /// rules as part of it's narrative along with other profiles, value sets, etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "implicitRules")]
    pub implicit_rules: Option<Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    ///
    /// ## Implementation Notes
    /// Language is provided to support indexing and accessibility (typically,
    /// services such as text to speech use the language tag). The html language tag
    /// in the narrative applies to the narrative. The language tag on the resource
    /// may be used to specify the language of other presentations generated from the
    /// data in the resource. Not all the content has to be in the base language. The
    /// Resource.language should not be assumed to apply to the narrative
    /// automatically. If a language is specified, it should it also be specified on
    /// the div element in the html (see rules in HTML5 for information about the
    /// relationship between xml:lang and the html lang attribute).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: A human language.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/languages
    pub language: Option<Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can be
    /// used to represent the content of the resource to a human. The narrative need
    /// not encode all the structured data, but is required to contain sufficient
    /// detail to make it "clinically safe" for a human to just read the narrative.
    /// Resource definitions may define what content should be represented in the
    /// narrative to ensure clinical safety.
    ///
    /// ## Implementation Notes
    /// Contained resources do not have narrative. Resources that are not contained
    /// SHOULD have a narrative. In some cases, a resource may only have text with
    /// little or no additional discrete data (as long as all minOccurs=1 elements
    /// are satisfied). This may be necessary for data from legacy systems where
    /// information is captured as a "text blob" or where text is additionally
    /// entered raw or narrated and encoded information is added later.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// narrative, html, xhtml, display
    pub text: Option<Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, and nor can
    /// they have their own independent transaction scope.
    ///
    /// ## Implementation Notes
    /// This should never be done when the content can be identified properly, as
    /// once identification is lost, it is extremely difficult (and context
    /// dependent) to restore it again. Contained resources may have profiles and
    /// tags In their meta elements, but SHALL NOT have security labels.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Aliases
    /// inline resources, anonymous resources, contained resources
    pub contained: Option<Vec<Resource>>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is a
    /// set of requirements that SHALL be met as part of the definition of the
    /// extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource and that modifies the understanding of the element
    /// that contains it and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer is allowed to define an extension, there is a set of requirements
    /// that SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the resource that contains them
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Canonical identifier for this compartment definition, represented as a URI (globally unique)
    ///
    /// An absolute URI that is used to identify this compartment definition when it
    /// is referenced in a specification, model, design or an instance; also called
    /// its canonical identifier. This SHOULD be globally unique and SHOULD be a
    /// literal address at which at which an authoritative instance of this
    /// compartment definition is (or will be) published. This URL can be the target
    /// of a canonical reference. It SHALL remain the same when the compartment
    /// definition is stored on different servers.
    ///
    /// ## Requirements
    /// Allows the compartment definition to be referenced by a single globally
    /// unique identifier.
    ///
    /// ## Implementation Notes
    /// Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.
    /// Multiple instances may share the same URL if they have a distinct version.
    ///
    /// The determination of when to create a new version of a resource (same url,
    /// new version) vs. defining a new artifact is up to the author. Considerations
    /// for making this decision are found in [Technical and Business
    /// Versions](resource.html#versions).
    ///
    /// In some cases, the resource can no longer be found at the stated url, but the
    /// url itself cannot change. Implementations can use the
    /// [meta.source](resource.html#meta) element to indicate where the current
    /// master source of the resource can be found.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub url: Uri,
    /// Business version of the compartment definition
    ///
    /// The identifier that is used to identify this version of the compartment
    /// definition when it is referenced in a specification, model, design or
    /// instance. This is an arbitrary value managed by the compartment definition
    /// author and is not expected to be globally unique. For example, it might be a
    /// timestamp (e.g. yyyymmdd) if a managed version is not available. There is
    /// also no expectation that versions can be placed in a lexicographical
    /// sequence.
    ///
    /// ## Implementation Notes
    /// There may be different compartment definition instances that have the same
    /// identifier but different versions. The version can be appended to the url in
    /// a reference to allow a reference to a particular business version of the
    /// compartment definition with the format [url]|[version].
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub version: Option<String>,
    /// Name for this compartment definition (computer friendly)
    ///
    /// A natural language name identifying the compartment definition. This name
    /// should be usable as an identifier for the module by machine processing
    /// applications such as code generation.
    ///
    /// ## Requirements
    /// Support human navigation and code generation.
    ///
    /// ## Implementation Notes
    /// The name is not expected to be globally unique. The name should be a simple
    /// alphanumeric type name to ensure that it is machine-processing friendly.This
    /// is often the same as the code for the parameter, but does not need to be.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: inv-0
    pub name: String,
    /// draft | active | retired | unknown
    ///
    /// The status of this compartment definition. Enables tracking the life-cycle of
    /// the content.
    ///
    /// ## Implementation Notes
    /// Allows filtering of compartment definitions that are appropriate for use
    /// versus not.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This is labeled as "Is Modifier" because applications should not use a retired {{title}} without due consideration
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: The lifecycle status of an artifact.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/publication-status|4.0.1
    pub status: Code,
    /// For testing purposes, not real usage
    ///
    /// A Boolean value to indicate that this compartment definition is authored for
    /// testing purposes (or education/evaluation/marketing) and is not intended to
    /// be used for genuine usage.
    ///
    /// ## Requirements
    /// Enables experimental content to be developed following the same lifecycle
    /// that would be used for a production-level compartment definition.
    ///
    /// ## Implementation Notes
    /// Allows filtering of compartment definitions that are appropriate for use
    /// versus not.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub experimental: Option<Boolean>,
    /// Date last changed
    ///
    /// The date (and optionally time) when the compartment definition was published.
    /// The date must change when the business version changes and it must change if
    /// the status code changes. In addition, it should change when the substantive
    /// content of the compartment definition changes.
    ///
    /// ## Implementation Notes
    /// Note that this is not the same as the resource last-modified-date, since the
    /// resource may be a secondary representation of the compartment definition.
    /// Additional specific dates may be added as extensions or be found by
    /// consulting Provenances associated with past versions of the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// Revision Date
    pub date: Option<DateTime>,
    /// Name of the publisher (organization or individual)
    ///
    /// The name of the organization or individual that published the compartment
    /// definition.
    ///
    /// ## Requirements
    /// Helps establish the "authority/credibility" of the compartment definition.
    /// May also allow for contact.
    ///
    /// ## Implementation Notes
    /// Usually an organization but may be an individual. The publisher (or steward)
    /// of the compartment definition is the organization or individual primarily
    /// responsible for the maintenance and upkeep of the compartment definition.
    /// This is not necessarily the same individual or organization that developed
    /// and initially authored the content. The publisher is the primary point of
    /// contact for questions or issues with the compartment definition. This item
    /// SHOULD be populated unless the information is available from context.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub publisher: Option<String>,
    /// Contact details for the publisher
    ///
    /// Contact details to assist a user in finding and communicating with the
    /// publisher.
    ///
    /// ## Implementation Notes
    /// May be a web site, an email address, a telephone number, etc.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub contact: Option<Vec<ContactDetail>>,
    /// Natural language description of the compartment definition
    ///
    /// A free text natural language description of the compartment definition from a
    /// consumer's perspective.
    ///
    /// ## Implementation Notes
    /// This description can be used to capture details such as why the compartment
    /// definition was built, comments about misuse, instructions for clinical use
    /// and interpretation, literature references, examples from the paper world,
    /// etc. It is not a rendering of the compartment definition as conveyed in the
    /// 'text' field of the resource itself. This item SHOULD be populated unless the
    /// information is available from context (e.g. the language of the compartment
    /// definition is presumed to be the predominant language in the place the
    /// compartment definition was created).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub description: Option<Markdown>,
    /// The context that the content is intended to support
    ///
    /// The content was developed with a focus and intent of supporting the contexts
    /// that are listed. These contexts may be general categories (gender, age, ...)
    /// or may be references to specific programs (insurance plans, studies, ...) and
    /// may be used to assist with indexing and searching for appropriate compartment
    /// definition instances.
    ///
    /// ## Requirements
    /// Assist in searching for appropriate content.
    ///
    /// ## Implementation Notes
    /// When multiple useContexts are specified, there is no expectation that all or
    /// any of the contexts apply.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "useContext")]
    pub use_context: Option<Vec<UsageContext>>,
    /// Why this compartment definition is defined
    ///
    /// Explanation of why this compartment definition is needed and why it has been
    /// designed as it has.
    ///
    /// ## Implementation Notes
    /// This element does not describe the usage of the compartment definition.
    /// Instead, it provides traceability of ''why'' the resource is either needed or
    /// ''why'' it is defined as it is. This may be used to point to source materials
    /// or specifications that drove the structure of this compartment definition.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub purpose: Option<Markdown>,
    /// Patient | Encounter | RelatedPerson | Practitioner | Device
    ///
    /// Which compartment this definition describes.
    ///
    /// ## Implementation Notes
    /// Only the specification can define the compartments that can exist. Servers
    /// can choose to support them.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: Which type a compartment definition describes.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/compartment-type|4.0.1
    pub code: Code,
    /// Whether the search syntax is supported
    ///
    /// Whether the search syntax is supported,.
    ///
    /// ## Implementation Notes
    /// Servers may define and use compartments to manage logical access without
    /// implementing the compartment related syntax.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub search: Boolean,
    /// How a resource is related to the compartment
    ///
    /// Information about how a resource is related to the compartment.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub resource: Option<Vec<CompartmentDefinitionResource>>,
}

/// How a resource is related to the compartment
///
/// Information about how a resource is related to the compartment.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct CompartmentDefinitionResource {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Name of resource type
    ///
    /// The name of a resource supported by the server.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: One of the resource types defined as part of this version of FHIR.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/resource-types|4.0.1
    pub code: Code,
    /// Search Parameter Name, or chained parameters
    ///
    /// The name of a search parameter that represents the link to the compartment.
    /// More than one may be listed because a resource may be linked to a compartment
    /// in more than one way,.
    ///
    /// ## Implementation Notes
    /// If no search parameters are listed, then the resource is not linked to the
    /// compartment.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub param: Option<Vec<String>>,
    /// Additional documentation about the resource and compartment
    ///
    /// Additional documentation about the resource and compartment.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub documentation: Option<String>,
}
