// AUTO-GENERATED by atrius-fhir-generator (R5 CareTeam)
use crate::r5::*;

/// FHIR CareTeam type
///
/// The Care Team includes all the people and organizations who plan to
/// participate in the coordination and delivery of care.
///
/// ## Type: Resource type
/// Base type: http://hl7.org/fhir/StructureDefinition/DomainResource
///
/// ## Status: draft
/// FHIR Version: 5.0.0
///
/// See: [CareTeam](http://hl7.org/fhir/StructureDefinition/CareTeam)
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(
    summary_fields = "id,meta,implicit_rules,modifier_extension,identifier,status,category,name,subject,period,managing_organization"
)]
pub struct CareTeam {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    ///
    /// ## Implementation Notes
    /// Within the context of the FHIR RESTful interactions, the resource has an id
    /// except for cases like the create and conditional update. Otherwise, the use
    /// of the resouce id depends on the given use case.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    pub id: Option<String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub meta: Option<Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content. Often,
    /// this is a reference to an implementation guide that defines the special rules
    /// along with other profiles etc.
    ///
    /// ## Implementation Notes
    /// Asserting this rule set restricts the content to be only understood by a
    /// limited set of trading partners. This inherently limits the usefulness of the
    /// data in the long term. However, the existing health eco-system is highly
    /// fractured, and not yet ready to define, collect, and exchange data in a
    /// generally computable sense. Wherever possible, implementers and/or
    /// specification writers should avoid using this element. Often, when used, the
    /// URL is a reference to an implementation guide that defines these special
    /// rules as part of its narrative along with other profiles, value sets, etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies its meaning or interpretation
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "implicitRules")]
    pub implicit_rules: Option<Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    ///
    /// ## Implementation Notes
    /// Language is provided to support indexing and accessibility (typically,
    /// services such as text to speech use the language tag). The html language tag
    /// in the narrative applies to the narrative. The language tag on the resource
    /// may be used to specify the language of other presentations generated from the
    /// data in the resource. Not all the content has to be in the base language. The
    /// Resource.language should not be assumed to apply to the narrative
    /// automatically. If a language is specified, it should it also be specified on
    /// the div element in the html (see rules in HTML5 for information about the
    /// relationship between xml:lang and the html lang attribute).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: IETF language tag for a human language
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/all-languages|5.0.0
    pub language: Option<Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can be
    /// used to represent the content of the resource to a human. The narrative need
    /// not encode all the structured data, but is required to contain sufficient
    /// detail to make it "clinically safe" for a human to just read the narrative.
    /// Resource definitions may define what content should be represented in the
    /// narrative to ensure clinical safety.
    ///
    /// ## Implementation Notes
    /// Contained resources do not have a narrative. Resources that are not contained
    /// SHOULD have a narrative. In some cases, a resource may only have text with
    /// little or no additional discrete data (as long as all minOccurs=1 elements
    /// are satisfied). This may be necessary for data from legacy systems where
    /// information is captured as a "text blob" or where text is additionally
    /// entered raw or narrated and encoded information is added later.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// narrative, html, xhtml, display
    ///
    /// ## Conditions
    /// Used when: dom-6
    pub text: Option<Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, nor can they
    /// have their own independent transaction scope. This is allowed to be a
    /// Parameters resource if and only if it is referenced by a resource that
    /// provides context/meaning.
    ///
    /// ## Implementation Notes
    /// This should never be done when the content can be identified properly, as
    /// once identification is lost, it is extremely difficult (and context
    /// dependent) to restore it again. Contained resources may have profiles and
    /// tags in their meta elements, but SHALL NOT have security labels.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Aliases
    /// inline resources, anonymous resources, contained resources
    ///
    /// ## Conditions
    /// Used when: dom-2, dom-4, dom-3, dom-5
    pub contained: Option<Vec<Resource>>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource and that modifies the understanding of the element
    /// that contains it and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer is allowed to define an extension, there is a set of requirements
    /// that SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the resource that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// External Ids for this team
    ///
    /// Business identifiers assigned to this care team by the performer or other
    /// systems which remain constant as the resource is updated and propagates from
    /// server to server.
    ///
    /// ## Requirements
    /// Allows identification of the care team as it is known by various
    /// participating systems and in a way that remains consistent across servers.
    ///
    /// ## Implementation Notes
    /// This is a business identifier, not a resource identifier (see
    /// [discussion](resource.html#identifiers)). It is best practice for the
    /// identifier to only appear on a single resource instance, however business
    /// practices may occasionally dictate that multiple resource instances with the
    /// same identifier can exist - possibly even with different resource types. For
    /// example, multiple Patient and a Person resource instance might share the same
    /// social insurance number.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub identifier: Option<Vec<Identifier>>,
    /// proposed | active | suspended | inactive | entered-in-error
    ///
    /// Indicates the current state of the care team.
    ///
    /// ## Implementation Notes
    /// This element is labeled as a modifier because the status contains the code
    /// entered-in-error that marks the care team as not currently valid.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: Indicates the status of the care team.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/care-team-status|5.0.0
    pub status: Option<Code>,
    /// Type of team
    ///
    /// Identifies what kind of team. This is to support differentiation between
    /// multiple co-existing teams, such as care plan team, episode of care team,
    /// longitudinal care team.
    ///
    /// ## Requirements
    /// Used for filtering what teams(s) are retrieved and displayed to different
    /// types of users.
    ///
    /// ## Implementation Notes
    /// There may be multiple axis of categorization and one team may serve multiple
    /// purposes.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: Indicates the type of care team.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/care-team-category
    pub category: Option<Vec<CodeableConcept>>,
    /// Name of the team, such as crisis assessment team
    ///
    /// A label for human use intended to distinguish like teams. E.g. the "red" vs.
    /// "green" trauma teams.
    ///
    /// ## Implementation Notes
    /// The meaning/purpose of the team is conveyed in CareTeam.category. This
    /// element may also convey semantics of the team (e.g. "Red trauma team"), but
    /// its primary purpose is to distinguish between identical teams in a
    /// human-friendly way. ("Team 18735" isn't as friendly.).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub name: Option<String>,
    /// Who care team is for
    ///
    /// Identifies the patient or group whose intended care is handled by the team.
    ///
    /// ## Requirements
    /// Allows the team to care for a group (e.g. marriage) therapy.
    /// Allows for an organization to designate a team such as the PICC line team.
    ///
    /// ## Implementation Notes
    /// Use Group for care provision to all members of the group (e.g. group
    /// therapy). Use Patient for care provision to an individual patient.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// patient
    pub subject: Option<Reference>,
    /// Time period team covers
    ///
    /// Indicates when the team did (or is intended to) come into effect and end.
    ///
    /// ## Requirements
    /// Allows tracking what team(s) are in effect at a particular time.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub period: Option<Period>,
    /// Members of the team
    ///
    /// Identifies all people and organizations who are expected to be involved in
    /// the care team.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ctm-1**: CareTeam.participant.onBehalfOf can only be populated when CareTeam.participant.member is a Practitioner (error)
    ///   Expression: `onBehalfOf.exists() implies (member.resolve() is Practitioner)`
    /// - **ctm-2**: CareTeam.participant.role or CareTeam.participant.member exists (warning)
    ///   Expression: `role.exists() or member.exists()`
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub participant: Option<Vec<CareTeamParticipant>>,
    /// Why the care team exists
    ///
    /// Describes why the care team exists.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: Indicates the reason for the care team.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/clinical-findings
    pub reason: Option<Vec<CodeableReference>>,
    /// Organization responsible for the care team
    ///
    /// The organization responsible for the care team.
    ///
    /// ## Requirements
    /// Allows for multiple organizations to collaboratively manage
    /// cross-organizational, longitudinal care plan.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "managingOrganization")]
    pub managing_organization: Option<Vec<Reference>>,
    /// A contact detail for the care team (that applies to all members)
    ///
    /// A central contact detail for the care team (that applies to all members).
    ///
    /// ## Implementation Notes
    /// The ContactPoint.use code of home is not appropriate to use. These contacts
    /// are not the contact details of individual care team members.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub telecom: Option<Vec<ContactPoint>>,
    /// Comments made about the CareTeam
    ///
    /// Comments made about the CareTeam.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub note: Option<Vec<Annotation>>,
}

/// Choice of types for the coverage\[x\] field in CareTeamParticipant
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "coverage")]
pub enum CareTeamParticipantCoverage {
    /// Variant accepting the Period type.
    #[fhir_serde(rename = "coveragePeriod")]
    Period(Period),
    /// Variant accepting the Timing type.
    #[fhir_serde(rename = "coverageTiming")]
    Timing(Timing),
}

/// Members of the team
///
/// Identifies all people and organizations who are expected to be involved in
/// the care team.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ctm-1**: CareTeam.participant.onBehalfOf can only be populated when CareTeam.participant.member is a Practitioner (error)
///   Expression: `onBehalfOf.exists() implies (member.resolve() is Practitioner)`
/// - **ctm-2**: CareTeam.participant.role or CareTeam.participant.member exists (warning)
///   Expression: `role.exists() or member.exists()`
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(choice_elements = "coverage")]
pub struct CareTeamParticipant {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Type of involvement
    ///
    /// Indicates specific responsibility of an individual within the care team, such
    /// as "Primary care physician", "Trained social worker counselor", "Caregiver",
    /// etc.
    ///
    /// ## Implementation Notes
    /// Roles may sometimes be inferred by type of Practitioner. These are
    /// relationships that hold only within the context of the care team. General
    /// relationships should be handled as properties of the Patient resource
    /// directly. If a participant has multiple roles within the team, then there
    /// should be multiple participants.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: Indicates specific responsibility of an individual within the care team, such as "Primary physician", "Team coordinator", "Caregiver", etc.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/participant-role
    ///
    /// ## Conditions
    /// Used when: ctm-2
    pub role: Option<CodeableConcept>,
    /// Who is involved
    ///
    /// The specific person or organization who is participating/expected to
    /// participate in the care team.
    ///
    /// ## Implementation Notes
    /// Patient only needs to be listed if they have a role other than "subject of
    /// care".
    ///
    /// Member is optional because some participants may be known only by their role,
    /// particularly in draft plans.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: ctm-1, ctm-2
    pub member: Option<Reference>,
    /// Organization of the practitioner
    ///
    /// The organization of the practitioner.
    ///
    /// ## Requirements
    /// Practitioners can be associated with multiple organizations. This element
    /// indicates which organization they were acting on behalf of.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: ctm-1
    #[fhir_serde(rename = "onBehalfOf")]
    pub on_behalf_of: Option<Reference>,
    /// When the member is generally available within this care team
    ///
    /// When the member is generally available within this care team.
    ///
    /// ## Requirements
    /// To manage members who share the same role, but with different timing. For
    /// example, two physical therapists where one is available Monday through Friday
    /// whereas the other is available on the weekend.
    ///
    /// ## Implementation Notes
    /// This is populated while creating / managing the CareTeam to ensure there is
    /// coverage when servicing CarePlan activities from the Schedule.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(flatten)]
    pub coverage: Option<CareTeamParticipantCoverage>,
}
