// AUTO-GENERATED by atrius-fhir-generator (R5 GenomicStudy)
use crate::r5::*;

/// FHIR GenomicStudy type
///
/// A set of analyses performed to analyze and generate genomic data.
///
/// ## Type: Resource type
/// Base type: http://hl7.org/fhir/StructureDefinition/DomainResource
///
/// ## Status: draft
/// FHIR Version: 5.0.0
///
/// See: [GenomicStudy](http://hl7.org/fhir/StructureDefinition/GenomicStudy)
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(
    summary_fields = "id,meta,implicit_rules,modifier_extension,identifier,status,r#type,subject,encounter"
)]
pub struct GenomicStudy {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    ///
    /// ## Implementation Notes
    /// Within the context of the FHIR RESTful interactions, the resource has an id
    /// except for cases like the create and conditional update. Otherwise, the use
    /// of the resouce id depends on the given use case.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    pub id: Option<String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub meta: Option<Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content. Often,
    /// this is a reference to an implementation guide that defines the special rules
    /// along with other profiles etc.
    ///
    /// ## Implementation Notes
    /// Asserting this rule set restricts the content to be only understood by a
    /// limited set of trading partners. This inherently limits the usefulness of the
    /// data in the long term. However, the existing health eco-system is highly
    /// fractured, and not yet ready to define, collect, and exchange data in a
    /// generally computable sense. Wherever possible, implementers and/or
    /// specification writers should avoid using this element. Often, when used, the
    /// URL is a reference to an implementation guide that defines these special
    /// rules as part of its narrative along with other profiles, value sets, etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies its meaning or interpretation
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "implicitRules")]
    pub implicit_rules: Option<Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    ///
    /// ## Implementation Notes
    /// Language is provided to support indexing and accessibility (typically,
    /// services such as text to speech use the language tag). The html language tag
    /// in the narrative applies to the narrative. The language tag on the resource
    /// may be used to specify the language of other presentations generated from the
    /// data in the resource. Not all the content has to be in the base language. The
    /// Resource.language should not be assumed to apply to the narrative
    /// automatically. If a language is specified, it should it also be specified on
    /// the div element in the html (see rules in HTML5 for information about the
    /// relationship between xml:lang and the html lang attribute).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: IETF language tag for a human language
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/all-languages|5.0.0
    pub language: Option<Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can be
    /// used to represent the content of the resource to a human. The narrative need
    /// not encode all the structured data, but is required to contain sufficient
    /// detail to make it "clinically safe" for a human to just read the narrative.
    /// Resource definitions may define what content should be represented in the
    /// narrative to ensure clinical safety.
    ///
    /// ## Implementation Notes
    /// Contained resources do not have a narrative. Resources that are not contained
    /// SHOULD have a narrative. In some cases, a resource may only have text with
    /// little or no additional discrete data (as long as all minOccurs=1 elements
    /// are satisfied). This may be necessary for data from legacy systems where
    /// information is captured as a "text blob" or where text is additionally
    /// entered raw or narrated and encoded information is added later.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// narrative, html, xhtml, display
    ///
    /// ## Conditions
    /// Used when: dom-6
    pub text: Option<Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, nor can they
    /// have their own independent transaction scope. This is allowed to be a
    /// Parameters resource if and only if it is referenced by a resource that
    /// provides context/meaning.
    ///
    /// ## Implementation Notes
    /// This should never be done when the content can be identified properly, as
    /// once identification is lost, it is extremely difficult (and context
    /// dependent) to restore it again. Contained resources may have profiles and
    /// tags in their meta elements, but SHALL NOT have security labels.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Aliases
    /// inline resources, anonymous resources, contained resources
    ///
    /// ## Conditions
    /// Used when: dom-2, dom-4, dom-3, dom-5
    pub contained: Option<Vec<Resource>>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource and that modifies the understanding of the element
    /// that contains it and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer is allowed to define an extension, there is a set of requirements
    /// that SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the resource that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Identifiers for this genomic study
    ///
    /// Identifiers for this genomic study.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub identifier: Option<Vec<Identifier>>,
    /// registered | available | cancelled | entered-in-error | unknown
    ///
    /// The status of the genomic study.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: The status of the GenomicStudy.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-status|5.0.0
    pub status: Code,
    /// The type of the study (e.g., Familial variant segregation, Functional variation detection, or Gene expression profiling)
    ///
    /// The type of the study, e.g., Familial variant segregation, Functional
    /// variation detection, or Gene expression profiling.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The type relevant to GenomicStudy.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-type
    #[fhir_serde(rename = "type")]
    pub r#type: Option<Vec<CodeableConcept>>,
    /// The primary subject of the genomic study
    ///
    /// The primary subject of the genomic study.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub subject: Reference,
    /// The healthcare event with which this genomics study is associated
    ///
    /// The healthcare event with which this genomics study is associated.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub encounter: Option<Reference>,
    /// When the genomic study was started
    ///
    /// When the genomic study was started.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "startDate")]
    pub start_date: Option<DateTime>,
    /// Event resources that the genomic study is based on
    ///
    /// Event resources that the genomic study is based on.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "basedOn")]
    pub based_on: Option<Vec<Reference>>,
    /// Healthcare professional who requested or referred the genomic study
    ///
    /// Healthcare professional who requested or referred the genomic study.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub referrer: Option<Reference>,
    /// Healthcare professionals who interpreted the genomic study
    ///
    /// Healthcare professionals who interpreted the genomic study.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub interpreter: Option<Vec<Reference>>,
    /// Why the genomic study was performed
    ///
    /// Why the genomic study was performed.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub reason: Option<Vec<CodeableReference>>,
    /// The defined protocol that describes the study
    ///
    /// The defined protocol that describes the study.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "instantiatesCanonical")]
    pub instantiates_canonical: Option<Canonical>,
    /// The URL pointing to an externally maintained protocol that describes the study
    ///
    /// The URL pointing to an externally maintained protocol that describes the
    /// study.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "instantiatesUri")]
    pub instantiates_uri: Option<Uri>,
    /// Comments related to the genomic study
    ///
    /// Comments related to the genomic study.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub note: Option<Vec<Annotation>>,
    /// Description of the genomic study
    ///
    /// Description of the genomic study.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub description: Option<Markdown>,
    /// Genomic Analysis Event
    ///
    /// The details about a specific analysis that was performed in this
    /// GenomicStudy.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub analysis: Option<Vec<GenomicStudyAnalysis>>,
}

/// Genomic Analysis Event
///
/// The details about a specific analysis that was performed in this
/// GenomicStudy.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct GenomicStudyAnalysis {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Identifiers for the analysis event
    ///
    /// Identifiers for the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub identifier: Option<Vec<Identifier>>,
    /// Type of the methods used in the analysis (e.g., FISH, Karyotyping, MSI)
    ///
    /// Type of the methods used in the analysis, e.g., Fluorescence in situ
    /// hybridization (FISH), Karyotyping, or Microsatellite instability testing
    /// (MSI).
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The method type of the GenomicStudy analysis.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-methodtype
    #[fhir_serde(rename = "methodType")]
    pub method_type: Option<Vec<CodeableConcept>>,
    /// Type of the genomic changes studied in the analysis (e.g., DNA, RNA, or AA change)
    ///
    /// Type of the genomic changes studied in the analysis, e.g., DNA, RNA, or amino
    /// acid change.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The change type relevant to GenomicStudy analysis.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-changetype
    #[fhir_serde(rename = "changeType")]
    pub change_type: Option<Vec<CodeableConcept>>,
    /// Genome build that is used in this analysis
    ///
    /// The reference genome build that is used in this analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: extensible
    /// - **Description**: Human reference sequence NCBI build ID
    /// - **ValueSet**: http://loinc.org/vs/LL1040-6
    #[fhir_serde(rename = "genomeBuild")]
    pub genome_build: Option<CodeableConcept>,
    /// The defined protocol that describes the analysis
    ///
    /// The defined protocol that describes the analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "instantiatesCanonical")]
    pub instantiates_canonical: Option<Canonical>,
    /// The URL pointing to an externally maintained protocol that describes the analysis
    ///
    /// The URL pointing to an externally maintained protocol that describes the
    /// analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "instantiatesUri")]
    pub instantiates_uri: Option<Uri>,
    /// Name of the analysis event (human friendly)
    ///
    /// Name of the analysis event (human friendly).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub title: Option<String>,
    /// What the genomic analysis is about, when it is not about the subject of record
    ///
    /// The focus of a genomic analysis when it is not the patient of record
    /// representing something or someone associated with the patient such as a
    /// spouse, parent, child, or sibling. For example, in trio testing, the
    /// GenomicStudy.subject would be the child (proband) and the
    /// GenomicStudy.analysis.focus of a specific analysis would be the parent.
    ///
    /// ## Implementation Notes
    /// If the focus of the analysis is not known, the value of this field SHALL use
    /// the data absent extension.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub focus: Option<Vec<Reference>>,
    /// The specimen used in the analysis event
    ///
    /// The specimen used in the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub specimen: Option<Vec<Reference>>,
    /// The date of the analysis event
    ///
    /// The date of the analysis event.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub date: Option<DateTime>,
    /// Any notes capture with the analysis event
    ///
    /// Any notes capture with the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub note: Option<Vec<Annotation>>,
    /// The protocol that was performed for the analysis event
    ///
    /// The protocol that was performed for the analysis event.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "protocolPerformed")]
    pub protocol_performed: Option<Reference>,
    /// The genomic regions to be studied in the analysis (BED file)
    ///
    /// The genomic regions to be studied in the analysis (BED file).
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "regionsStudied")]
    pub regions_studied: Option<Vec<Reference>>,
    /// Genomic regions actually called in the analysis event (BED file)
    ///
    /// Genomic regions actually called in the analysis event (BED file).
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "regionsCalled")]
    pub regions_called: Option<Vec<Reference>>,
    /// Inputs for the analysis event
    ///
    /// Inputs for the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub input: Option<Vec<GenomicStudyAnalysisInput>>,
    /// Outputs for the analysis event
    ///
    /// Outputs for the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub output: Option<Vec<GenomicStudyAnalysisOutput>>,
    /// Performer for the analysis event
    ///
    /// Performer for the analysis event.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub performer: Option<Vec<GenomicStudyAnalysisPerformer>>,
    /// Devices used for the analysis (e.g., instruments, software), with settings and parameters
    ///
    /// Devices used for the analysis (e.g., instruments, software), with settings
    /// and parameters.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub device: Option<Vec<GenomicStudyAnalysisDevice>>,
}

/// Devices used for the analysis (e.g., instruments, software), with settings and parameters
///
/// Devices used for the analysis (e.g., instruments, software), with settings
/// and parameters.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct GenomicStudyAnalysisDevice {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Device used for the analysis
    ///
    /// Device used for the analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub device: Option<Reference>,
    /// Specific function for the device used for the analysis
    ///
    /// Specific function for the device used for the analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub function: Option<CodeableConcept>,
}

/// Choice of types for the generatedBy\[x\] field in GenomicStudyAnalysisInput
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "generatedBy")]
pub enum GenomicStudyAnalysisInputGeneratedBy {
    /// Variant accepting the Identifier type.
    #[fhir_serde(rename = "generatedByIdentifier")]
    Identifier(Identifier),
    /// Variant accepting the Reference type.
    #[fhir_serde(rename = "generatedByReference")]
    Reference(Reference),
}

/// Inputs for the analysis event
///
/// Inputs for the analysis event.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(choice_elements = "generatedBy")]
pub struct GenomicStudyAnalysisInput {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// File containing input data
    ///
    /// File containing input data.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub file: Option<Reference>,
    /// Type of input data (e.g., BAM, CRAM, or FASTA)
    ///
    /// Type of input data, e.g., BAM, CRAM, or FASTA.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The data format of the data file.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-dataformat
    #[fhir_serde(rename = "type")]
    pub r#type: Option<CodeableConcept>,
    /// The analysis event or other GenomicStudy that generated this input file
    ///
    /// The analysis event or other GenomicStudy that generated this input file.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(flatten)]
    pub generated_by: Option<GenomicStudyAnalysisInputGeneratedBy>,
}

/// Outputs for the analysis event
///
/// Outputs for the analysis event.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct GenomicStudyAnalysisOutput {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// File containing output data
    ///
    /// File containing output data.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub file: Option<Reference>,
    /// Type of output data (e.g., VCF, MAF, or BAM)
    ///
    /// Type of output data, e.g., VCF, MAF, or BAM.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The data format of the data file.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/genomicstudy-dataformat
    #[fhir_serde(rename = "type")]
    pub r#type: Option<CodeableConcept>,
}

/// Performer for the analysis event
///
/// Performer for the analysis event.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct GenomicStudyAnalysisPerformer {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The organization, healthcare professional, or others who participated in performing this analysis
    ///
    /// The organization, healthcare professional, or others who participated in
    /// performing this analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub actor: Option<Reference>,
    /// Role of the actor for this analysis
    ///
    /// Role of the actor for this analysis.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub role: Option<CodeableConcept>,
}
