//! Embedded core terminology.
//!
//! A [`TerminologyProvider`] backed by the FHIR core value sets that can be
//! expanded **offline** — every `compose.include` names a `complete` CodeSystem
//! shipped in the spec bundle, with no filters or nested value-set references.
//! One gzipped map per enabled FHIR version, generated by the
//! `generate-terminology` binary and committed under `packs/` (the same
//! committed-generated-artifact workflow as the schema packs).
//!
//! Its purpose is required-binding validation without a terminology server: a
//! `code` bound to `administrative-gender` must be one of `male | female |
//! other | unknown`, so `masculino` (a Spanish *display*, not a FHIR code) is
//! rejected. Value sets that need a live server (SNOMED, LOINC, filtered
//! includes) are absent from the map; for those the provider returns `Ok(true)`
//! — "not disproved here" — so it never blocks on codes it cannot check.

use crate::effects::{CodedValue, Deferred, TerminologyError, TerminologyProvider, coded_value};
use crate::engine::{ErrorKind, ValidationError};
use async_trait::async_trait;
use flate2::read::GzDecoder;
use helios_fhir::FhirVersion;
use serde_json::Value;
use std::collections::HashMap;
use std::io::Read;
use std::sync::{Arc, OnceLock};

#[cfg(feature = "R4")]
static R4_TX: &[u8] = include_bytes!("../packs/terminology_r4.json.gz");
#[cfg(feature = "R4B")]
static R4B_TX: &[u8] = include_bytes!("../packs/terminology_r4b.json.gz");
#[cfg(feature = "R5")]
static R5_TX: &[u8] = include_bytes!("../packs/terminology_r5.json.gz");
#[cfg(feature = "R6")]
static R6_TX: &[u8] = include_bytes!("../packs/terminology_r6.json.gz");

/// The embedded core value sets for a FHIR version. Parsed on first use;
/// subsequent calls return the shared instance.
pub fn core_terminology(version: FhirVersion) -> Arc<CoreTerminology> {
    match version {
        #[cfg(feature = "R4")]
        FhirVersion::R4 => {
            static TX: OnceLock<Arc<CoreTerminology>> = OnceLock::new();
            Arc::clone(TX.get_or_init(|| Arc::new(CoreTerminology::from_gz(R4_TX))))
        }
        #[cfg(feature = "R4B")]
        FhirVersion::R4B => {
            static TX: OnceLock<Arc<CoreTerminology>> = OnceLock::new();
            Arc::clone(TX.get_or_init(|| Arc::new(CoreTerminology::from_gz(R4B_TX))))
        }
        #[cfg(feature = "R5")]
        FhirVersion::R5 => {
            static TX: OnceLock<Arc<CoreTerminology>> = OnceLock::new();
            Arc::clone(TX.get_or_init(|| Arc::new(CoreTerminology::from_gz(R5_TX))))
        }
        #[cfg(feature = "R6")]
        FhirVersion::R6 => {
            static TX: OnceLock<Arc<CoreTerminology>> = OnceLock::new();
            Arc::clone(TX.get_or_init(|| Arc::new(CoreTerminology::from_gz(R6_TX))))
        }
    }
}

/// Codes of one value set, indexed by code → the systems that define it here.
type ValueSetCodes = HashMap<String, Vec<String>>;

/// An offline terminology provider over the embedded core value sets.
pub struct CoreTerminology {
    /// Value-set URL (version-stripped) → its expanded codes.
    sets: HashMap<String, ValueSetCodes>,
}

impl CoreTerminology {
    fn from_gz(bytes: &[u8]) -> Self {
        let mut decoder = GzDecoder::new(bytes);
        let mut json = Vec::new();
        decoder
            .read_to_end(&mut json)
            .expect("embedded terminology pack decompresses");
        let pairs: Vec<(String, Vec<(String, String)>)> =
            serde_json::from_slice(&json).expect("embedded terminology pack parses");
        let mut sets = HashMap::with_capacity(pairs.len());
        for (url, codes) in pairs {
            let mut by_code: ValueSetCodes = HashMap::new();
            for (system, code) in codes {
                by_code.entry(code).or_default().push(system);
            }
            sets.insert(url, by_code);
        }
        Self { sets }
    }

    /// `Some(true/false)` when the value set is known here; `None` when it is
    /// not embedded (needs a terminology server). `system == None` matches the
    /// code under any system in the set (a bare `code` whose system is implied
    /// by the binding).
    fn contains(&self, value_set: &str, system: Option<&str>, code: &str) -> Option<bool> {
        let set = self.sets.get(strip_version(value_set))?;
        let Some(systems) = set.get(code) else {
            return Some(false);
        };
        match system {
            Some(sys) => Some(systems.iter().any(|s| s == sys)),
            None => Some(true),
        }
    }

    /// `Some(true)` in-set, `Some(false)` definitely out, `None` can't judge
    /// offline (value set not embedded, or shape not coded). This is the sync
    /// core both `validate_code` and the editor's binding check share.
    fn member(&self, value_set: &str, coded: &CodedValue) -> Option<bool> {
        match coded {
            CodedValue::Code(code) => self.contains(value_set, None, code),
            CodedValue::Coding(coding) => {
                let (system, code) = coding_parts(coding);
                self.contains(value_set, system, code?)
            }
            CodedValue::CodeableConcept(cc) => {
                let codings = cc
                    .get("coding")
                    .and_then(Value::as_array)
                    .filter(|c| !c.is_empty())?;
                let mut saw_false = false;
                for coding in codings {
                    let (system, code) = coding_parts(coding);
                    let Some(code) = code else { continue };
                    match self.contains(value_set, system, code) {
                        Some(true) => return Some(true),
                        Some(false) => saw_false = true,
                        None => return None, // any unembedded coding → can't judge the whole concept
                    }
                }
                saw_false.then_some(false)
            }
        }
    }

    /// Required-binding violations among `deferred`, checked offline against the
    /// embedded core value sets. Bindings whose value set is not embedded (needs
    /// a terminology server) are skipped, not guessed. Lets a synchronous caller
    /// (the resource editor) surface the same binding errors the async effects
    /// pass would, without a terminology server.
    pub fn required_binding_errors(&self, deferred: &[Deferred]) -> Vec<ValidationError> {
        let mut errors = Vec::new();
        for d in deferred {
            let Deferred::Binding {
                path,
                binding,
                value,
                type_hint,
            } = d
            else {
                continue;
            };
            if binding.strength.as_deref() != Some("required") {
                continue;
            }
            let Some(coded) = coded_value(value, type_hint.as_deref()) else {
                continue;
            };
            if self.member(&binding.value_set, &coded) == Some(false) {
                errors.push(ValidationError::new(
                    ErrorKind::TerminologyBinding,
                    path.clone(),
                    format!(
                        "code is not in the required value set '{}'",
                        strip_version(&binding.value_set)
                    ),
                ));
            }
        }
        errors
    }
}

/// Strips a `|version` suffix from a canonical URL (`…/administrative-gender|4.0.1`).
fn strip_version(url: &str) -> &str {
    url.split('|').next().unwrap_or(url)
}

fn coding_parts(coding: &Value) -> (Option<&str>, Option<&str>) {
    (
        coding.get("system").and_then(Value::as_str),
        coding.get("code").and_then(Value::as_str),
    )
}

#[async_trait]
impl TerminologyProvider for CoreTerminology {
    async fn validate_code(
        &self,
        value_set: &str,
        coded: &CodedValue,
    ) -> Result<bool, TerminologyError> {
        // Unknown value set / non-coded shape → not disproved here (`Ok(true)`);
        // only a definite `Some(false)` from `member` is a binding failure.
        Ok(self.member(value_set, coded).unwrap_or(true))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "R4")]
    #[tokio::test]
    async fn rejects_a_non_code_but_accepts_the_real_codes() {
        let tx = core_terminology(FhirVersion::R4);
        let vs = "http://hl7.org/fhir/ValueSet/administrative-gender";
        for good in ["male", "female", "other", "unknown"] {
            assert!(
                tx.validate_code(vs, &CodedValue::Code(good.into()))
                    .await
                    .unwrap(),
                "{good} is a valid administrative-gender code"
            );
        }
        // "masculino" is a Spanish display, not a FHIR code.
        assert!(
            !tx.validate_code(vs, &CodedValue::Code("masculino".into()))
                .await
                .unwrap(),
            "masculino is not an administrative-gender code"
        );
    }

    #[cfg(feature = "R4")]
    #[tokio::test]
    async fn unknown_value_set_is_not_disproved() {
        let tx = core_terminology(FhirVersion::R4);
        // A value set that needs a live server is absent from the pack.
        let res = tx
            .validate_code(
                "http://hl7.org/fhir/ValueSet/example-not-embedded",
                &CodedValue::Code("anything".into()),
            )
            .await
            .unwrap();
        assert!(res, "an unembedded value set must not be disproved offline");
    }
}
