// @generated by fhir-valueset-gen
// DO NOT EDIT MANUALLY

//! Diet
//!
//! This value set defines a set of codes that can be used to indicate dietary preferences or restrictions a patient may have.

use super::super::super::{CodeableConcept, Coding};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum Diet {
    Vegetarian,
    DairyFree,
    NutFree,
    GlutenFree,
    Vegan,
    Halal,
    Kosher,
}

impl Diet {
    pub const URL: &'static str = "http://terminology.hl7.org/CodeSystem/diet";
    pub const VERSION: &'static str = "4.0.1";
    pub const STATUS: &'static str = "draft";
    pub const CONTENT: &'static str = "complete";
    pub const EXPERIMENTAL: bool = false;
    pub const CASE_SENSITIVE: bool = true;
    pub const HAS_CONCEPTS: bool = true;

    pub fn as_code(self) -> &'static str {
        match self {
            Self::Vegetarian => "vegetarian",
            Self::DairyFree => "dairy-free",
            Self::NutFree => "nut-free",
            Self::GlutenFree => "gluten-free",
            Self::Vegan => "vegan",
            Self::Halal => "halal",
            Self::Kosher => "kosher",
        }
    }

    pub fn try_from_code(code: &str) -> Option<Self> {
        Some(match code {
            "vegetarian" => Self::Vegetarian,
            "dairy-free" => Self::DairyFree,
            "nut-free" => Self::NutFree,
            "gluten-free" => Self::GlutenFree,
            "vegan" => Self::Vegan,
            "halal" => Self::Halal,
            "kosher" => Self::Kosher,
            _ => return None,
        })
    }

    pub fn display(self) -> Option<&'static str> {
        match self {
            Self::Vegetarian => Some("Vegetarian"),
            Self::DairyFree => Some("Dairy Free"),
            Self::NutFree => Some("Nut Free"),
            Self::GlutenFree => Some("Gluten Free"),
            Self::Vegan => Some("Vegan"),
            Self::Halal => Some("Halal"),
            Self::Kosher => Some("Kosher"),
        }
    }

    pub fn definition(self) -> Option<&'static str> {
        match self {
            Self::Vegetarian => Some("Food without meat, poultry or seafood."),
            Self::DairyFree => Some("Excludes dairy products."),
            Self::NutFree => Some("Excludes ingredients containing nuts."),
            Self::GlutenFree => Some("Excludes ingredients containing gluten."),
            Self::Vegan => Some(
                "Food without meat, poultry, seafood, eggs, dairy products and other animal-derived substances.",
            ),
            Self::Halal => Some("Foods that conform to Islamic law."),
            Self::Kosher => Some("Foods that conform to Jewish dietary law."),
        }
    }

    pub fn parent_code(self) -> Option<&'static str> {
        match self {
            Self::Vegetarian => None,
            Self::DairyFree => None,
            Self::NutFree => None,
            Self::GlutenFree => None,
            Self::Vegan => None,
            Self::Halal => None,
            Self::Kosher => None,
        }
    }

    pub fn level(self) -> u16 {
        match self {
            Self::Vegetarian => 0,
            Self::DairyFree => 0,
            Self::NutFree => 0,
            Self::GlutenFree => 0,
            Self::Vegan => 0,
            Self::Halal => 0,
            Self::Kosher => 0,
        }
    }
    pub fn to_coding(self) -> Coding {
        Coding {
            id: None,
            extension: None,
            system: Some(Self::URL.to_string().into()),
            version: Some(Self::VERSION.to_string().into()),
            code: Some(self.as_code().to_string().into()),
            display: self.display().map(|d| d.to_string().into()),
            user_selected: None,
        }
    }

    pub fn to_codeable_concept(self) -> CodeableConcept {
        let coding = self.to_coding();
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: self.display().map(|d| d.to_string().into()),
        }
    }

    pub fn matches_coding(self, coding: &Coding) -> bool {
        let system = coding.system.as_ref().and_then(|e| e.value.as_deref());
        let code = coding.code.as_ref().and_then(|e| e.value.as_deref());
        system == Some(Self::URL) && code == Some(self.as_code())
    }

    pub fn matches_codeable_concept(self, cc: &CodeableConcept) -> bool {
        cc.coding
            .as_ref()
            .map(|v| {
                v.iter().any(|c| {
                    let system = c.system.as_ref().and_then(|e| e.value.as_deref());
                    let code = c.code.as_ref().and_then(|e| e.value.as_deref());
                    system == Some(Self::URL) && code == Some(self.as_code())
                })
            })
            .unwrap_or(false)
    }
}
