// @generated by fhir-valueset-gen
// DO NOT EDIT MANUALLY

//! Financial Task Codes
//!
//! This value set includes Financial Task codes.

use super::super::super::{CodeableConcept, Coding};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum FinancialTaskCodes {
    Cancel,
    Poll,
    Release,
    Reprocess,
    Status,
}

impl FinancialTaskCodes {
    pub const URL: &'static str = "http://terminology.hl7.org/CodeSystem/financialtaskcode";
    pub const VERSION: &'static str = "4.0.1";
    pub const STATUS: &'static str = "draft";
    pub const CONTENT: &'static str = "complete";
    pub const EXPERIMENTAL: bool = false;
    pub const CASE_SENSITIVE: bool = true;
    pub const HAS_CONCEPTS: bool = true;

    pub fn as_code(self) -> &'static str {
        match self {
            Self::Cancel => "cancel",
            Self::Poll => "poll",
            Self::Release => "release",
            Self::Reprocess => "reprocess",
            Self::Status => "status",
        }
    }

    pub fn try_from_code(code: &str) -> Option<Self> {
        Some(match code {
            "cancel" => Self::Cancel,
            "poll" => Self::Poll,
            "release" => Self::Release,
            "reprocess" => Self::Reprocess,
            "status" => Self::Status,
            _ => return None,
        })
    }

    pub fn display(self) -> Option<&'static str> {
        match self {
            Self::Cancel => Some("Cancel"),
            Self::Poll => Some("Poll"),
            Self::Release => Some("Release"),
            Self::Reprocess => Some("Reprocess"),
            Self::Status => Some("Status check"),
        }
    }

    pub fn definition(self) -> Option<&'static str> {
        match self {
            Self::Cancel => Some(
                "Cancel or reverse a resource, such as a claim or preauthorization, which is in-process or complete.",
            ),
            Self::Poll => Some("Retrieve selected or all queued resources or messages."),
            Self::Release => Some(
                "Release any reserved funds or material obligations associated with a resource. For example, any unused but reserved funds or treatment allowance associated with a preauthorization once treatment is complete.",
            ),
            Self::Reprocess => Some(
                "Indication that the processing of a resource, such as a claim, for some or all of the required work is now being requested.",
            ),
            Self::Status => Some(
                "Check on the processing status of a resource such as the adjudication of a claim.",
            ),
        }
    }

    pub fn parent_code(self) -> Option<&'static str> {
        match self {
            Self::Cancel => None,
            Self::Poll => None,
            Self::Release => None,
            Self::Reprocess => None,
            Self::Status => None,
        }
    }

    pub fn level(self) -> u16 {
        match self {
            Self::Cancel => 0,
            Self::Poll => 0,
            Self::Release => 0,
            Self::Reprocess => 0,
            Self::Status => 0,
        }
    }
    pub fn to_coding(self) -> Coding {
        Coding {
            id: None,
            extension: None,
            system: Some(Self::URL.to_string().into()),
            version: Some(Self::VERSION.to_string().into()),
            code: Some(self.as_code().to_string().into()),
            display: self.display().map(|d| d.to_string().into()),
            user_selected: None,
        }
    }

    pub fn to_codeable_concept(self) -> CodeableConcept {
        let coding = self.to_coding();
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: self.display().map(|d| d.to_string().into()),
        }
    }

    pub fn matches_coding(self, coding: &Coding) -> bool {
        let system = coding.system.as_ref().and_then(|e| e.value.as_deref());
        let code = coding.code.as_ref().and_then(|e| e.value.as_deref());
        system == Some(Self::URL) && code == Some(self.as_code())
    }

    pub fn matches_codeable_concept(self, cc: &CodeableConcept) -> bool {
        cc.coding
            .as_ref()
            .map(|v| {
                v.iter().any(|c| {
                    let system = c.system.as_ref().and_then(|e| e.value.as_deref());
                    let code = c.code.as_ref().and_then(|e| e.value.as_deref());
                    system == Some(Self::URL) && code == Some(self.as_code())
                })
            })
            .unwrap_or(false)
    }
}
