// @generated by fhir-valueset-gen
// DO NOT EDIT MANUALLY

//! Process Priority Codes
//!
//! This value set includes the financial processing priority codes.

use super::super::super::{CodeableConcept, Coding};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum ProcessPriorityCodes {
    Stat,
    Normal,
    Deferred,
}

impl ProcessPriorityCodes {
    pub const URL: &'static str = "http://terminology.hl7.org/CodeSystem/processpriority";
    pub const VERSION: &'static str = "4.0.1";
    pub const STATUS: &'static str = "draft";
    pub const CONTENT: &'static str = "complete";
    pub const EXPERIMENTAL: bool = false;
    pub const CASE_SENSITIVE: bool = true;
    pub const HAS_CONCEPTS: bool = true;

    pub fn as_code(self) -> &'static str {
        match self {
            Self::Stat => "stat",
            Self::Normal => "normal",
            Self::Deferred => "deferred",
        }
    }

    pub fn try_from_code(code: &str) -> Option<Self> {
        Some(match code {
            "stat" => Self::Stat,
            "normal" => Self::Normal,
            "deferred" => Self::Deferred,
            _ => return None,
        })
    }

    pub fn display(self) -> Option<&'static str> {
        match self {
            Self::Stat => Some("Immediate"),
            Self::Normal => Some("Normal"),
            Self::Deferred => Some("Deferred"),
        }
    }

    pub fn definition(self) -> Option<&'static str> {
        match self {
            Self::Stat => Some("Immediately in real time."),
            Self::Normal => Some("With best effort."),
            Self::Deferred => Some("Later, when possible."),
        }
    }

    pub fn parent_code(self) -> Option<&'static str> {
        match self {
            Self::Stat => None,
            Self::Normal => None,
            Self::Deferred => None,
        }
    }

    pub fn level(self) -> u16 {
        match self {
            Self::Stat => 0,
            Self::Normal => 0,
            Self::Deferred => 0,
        }
    }
    pub fn to_coding(self) -> Coding {
        Coding {
            id: None,
            extension: None,
            system: Some(Self::URL.to_string().into()),
            version: Some(Self::VERSION.to_string().into()),
            code: Some(self.as_code().to_string().into()),
            display: self.display().map(|d| d.to_string().into()),
            user_selected: None,
        }
    }

    pub fn to_codeable_concept(self) -> CodeableConcept {
        let coding = self.to_coding();
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: self.display().map(|d| d.to_string().into()),
        }
    }

    pub fn matches_coding(self, coding: &Coding) -> bool {
        let system = coding.system.as_ref().and_then(|e| e.value.as_deref());
        let code = coding.code.as_ref().and_then(|e| e.value.as_deref());
        system == Some(Self::URL) && code == Some(self.as_code())
    }

    pub fn matches_codeable_concept(self, cc: &CodeableConcept) -> bool {
        cc.coding
            .as_ref()
            .map(|v| {
                v.iter().any(|c| {
                    let system = c.system.as_ref().and_then(|e| e.value.as_deref());
                    let code = c.code.as_ref().and_then(|e| e.value.as_deref());
                    system == Some(Self::URL) && code == Some(self.as_code())
                })
            })
            .unwrap_or(false)
    }
}
