// AUTO-GENERATED by atrius-fhir-generator (R4B ClinicalUseDefinition)
use crate::r4b::*;

/// FHIR ClinicalUseDefinition type
///
/// A single issue - either an indication, contraindication, interaction or an
/// undesirable effect for a medicinal product, medication, device or procedure.
///
/// ## Type: Resource type
/// Base type: http://hl7.org/fhir/StructureDefinition/DomainResource
///
/// ## Status: draft
/// FHIR Version: 4.3.0
///
/// See: [ClinicalUseDefinition](http://hl7.org/fhir/StructureDefinition/ClinicalUseDefinition)
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(
    summary_fields = "id,meta,implicit_rules,identifier,r#type,category,subject,status,contraindication,indication,interaction,population,undesirable_effect,warning"
)]
pub struct ClinicalUseDefinition {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    ///
    /// ## Implementation Notes
    /// The only time that a resource does not have an id is when it is being
    /// submitted to the server using a create operation.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    pub id: Option<String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub meta: Option<Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content. Often,
    /// this is a reference to an implementation guide that defines the special rules
    /// along with other profiles etc.
    ///
    /// ## Implementation Notes
    /// Asserting this rule set restricts the content to be only understood by a
    /// limited set of trading partners. This inherently limits the usefulness of the
    /// data in the long term. However, the existing health eco-system is highly
    /// fractured, and not yet ready to define, collect, and exchange data in a
    /// generally computable sense. Wherever possible, implementers and/or
    /// specification writers should avoid using this element. Often, when used, the
    /// URL is a reference to an implementation guide that defines these special
    /// rules as part of it's narrative along with other profiles, value sets, etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies it's meaning or interpretation
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "implicitRules")]
    pub implicit_rules: Option<Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    ///
    /// ## Implementation Notes
    /// Language is provided to support indexing and accessibility (typically,
    /// services such as text to speech use the language tag). The html language tag
    /// in the narrative applies to the narrative. The language tag on the resource
    /// may be used to specify the language of other presentations generated from the
    /// data in the resource. Not all the content has to be in the base language. The
    /// Resource.language should not be assumed to apply to the narrative
    /// automatically. If a language is specified, it should it also be specified on
    /// the div element in the html (see rules in HTML5 for information about the
    /// relationship between xml:lang and the html lang attribute).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: IETF language tag
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/languages
    pub language: Option<Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can be
    /// used to represent the content of the resource to a human. The narrative need
    /// not encode all the structured data, but is required to contain sufficient
    /// detail to make it "clinically safe" for a human to just read the narrative.
    /// Resource definitions may define what content should be represented in the
    /// narrative to ensure clinical safety.
    ///
    /// ## Implementation Notes
    /// Contained resources do not have narrative. Resources that are not contained
    /// SHOULD have a narrative. In some cases, a resource may only have text with
    /// little or no additional discrete data (as long as all minOccurs=1 elements
    /// are satisfied). This may be necessary for data from legacy systems where
    /// information is captured as a "text blob" or where text is additionally
    /// entered raw or narrated and encoded information is added later.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// narrative, html, xhtml, display
    pub text: Option<Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, and nor can
    /// they have their own independent transaction scope.
    ///
    /// ## Implementation Notes
    /// This should never be done when the content can be identified properly, as
    /// once identification is lost, it is extremely difficult (and context
    /// dependent) to restore it again. Contained resources may have profiles and
    /// tags In their meta elements, but SHALL NOT have security labels.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **dom-r4b**: Containing new R4B resources within R4 resources may cause interoperability issues if instances are shared with R4 systems (warning)
    ///   Expression: `($this is Citation or $this is Evidence or $this is EvidenceReport or $this is EvidenceVariable or $this is MedicinalProductDefinition or $this is PackagedProductDefinition or $this is AdministrableProductDefinition or $this is Ingredient or $this is ClinicalUseDefinition or $this is RegulatedAuthorization or $this is SubstanceDefinition or $this is SubscriptionStatus or $this is SubscriptionTopic) implies (%resource is Citation or %resource is Evidence or %resource is EvidenceReport or %resource is EvidenceVariable or %resource is MedicinalProductDefinition or %resource is PackagedProductDefinition or %resource is AdministrableProductDefinition or %resource is Ingredient or %resource is ClinicalUseDefinition or %resource is RegulatedAuthorization or %resource is SubstanceDefinition or %resource is SubscriptionStatus or %resource is SubscriptionTopic)`
    ///
    /// ## Aliases
    /// inline resources, anonymous resources, contained resources
    pub contained: Option<Vec<Resource>>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is a
    /// set of requirements that SHALL be met as part of the definition of the
    /// extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource and that modifies the understanding of the element
    /// that contains it and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer is allowed to define an extension, there is a set of requirements
    /// that SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the resource that contains them
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// Business identifier for this issue
    ///
    /// Business identifier for this issue.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub identifier: Option<Vec<Identifier>>,
    /// indication | contraindication | interaction | undesirable-effect | warning
    ///
    /// indication | contraindication | interaction | undesirable-effect | warning.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: Overall defining type of this clinical use definition.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/clinical-use-definition-type|4.3.0
    #[fhir_serde(rename = "type")]
    pub r#type: Code,
    /// A categorisation of the issue, primarily for dividing warnings into subject heading areas such as "Pregnancy", "Overdose"
    ///
    /// A categorisation of the issue, primarily for dividing warnings into subject
    /// heading areas such as "Pregnancy and Lactation", "Overdose", "Effects on
    /// Ability to Drive and Use Machines".
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: A categorisation for a clinical use information item.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/clinical-use-definition-category
    pub category: Option<Vec<CodeableConcept>>,
    /// The medication or procedure for which this is an indication
    ///
    /// The medication or procedure for which this is an indication.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub subject: Option<Vec<Reference>>,
    /// Whether this is a current issue or one that has been retired etc
    ///
    /// Whether this is a current issue or one that has been retired etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: The lifecycle status of an artifact.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/publication-status
    pub status: Option<CodeableConcept>,
    /// Specifics for when this is a contraindication
    ///
    /// Specifics for when this is a contraindication.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    pub contraindication: Option<ClinicalUseDefinitionContraindication>,
    /// Specifics for when this is an indication
    ///
    /// Specifics for when this is an indication.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    pub indication: Option<ClinicalUseDefinitionIndication>,
    /// Specifics for when this is an interaction
    ///
    /// Specifics for when this is an interaction.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    pub interaction: Option<ClinicalUseDefinitionInteraction>,
    /// The population group to which this applies
    ///
    /// The population group to which this applies.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub population: Option<Vec<Reference>>,
    /// A possible negative outcome from the use of this treatment
    ///
    /// Describe the possible undesirable effects (negative outcomes) from the use of
    /// the medicinal product as treatment.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    #[fhir_serde(rename = "undesirableEffect")]
    pub undesirable_effect: Option<ClinicalUseDefinitionUndesirableEffect>,
    /// Critical environmental, health or physical risks or hazards. For example 'Do not operate heavy machinery', 'May cause drowsiness'
    ///
    /// A critical piece of information about environmental, health or physical risks
    /// or hazards that serve as caution to the user. For example 'Do not operate
    /// heavy machinery', 'May cause drowsiness', or 'Get medical advice/attention if
    /// you feel unwell'.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    pub warning: Option<ClinicalUseDefinitionWarning>,
}

/// Specifics for when this is a contraindication
///
/// Specifics for when this is a contraindication.
///
/// ## Cardinality: Optional (0..1)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct ClinicalUseDefinitionContraindication {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The situation that is being documented as contraindicating against this item
    ///
    /// The situation that is being documented as contraindicating against this item.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A symptom, disease or procedure.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-symptom-procedure
    #[fhir_serde(rename = "diseaseSymptomProcedure")]
    pub disease_symptom_procedure: Option<CodeableReference>,
    /// The status of the disease or symptom for the contraindication
    ///
    /// The status of the disease or symptom for the contraindication, for example
    /// "chronic" or "metastatic".
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The status of a disease or symptom.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-status
    #[fhir_serde(rename = "diseaseStatus")]
    pub disease_status: Option<CodeableReference>,
    /// A comorbidity (concurrent condition) or coinfection
    ///
    /// A comorbidity (concurrent condition) or coinfection.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A symptom, disease or procedure.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-symptom-procedure
    pub comorbidity: Option<Vec<CodeableReference>>,
    /// The indication which this is a contraidication for
    ///
    /// The indication which this is a contraidication for.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub indication: Option<Vec<Reference>>,
    /// Information about use of the product in relation to other therapies described as part of the contraindication
    ///
    /// Information about the use of the medicinal product in relation to other
    /// therapies described as part of the contraindication.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    #[fhir_serde(rename = "otherTherapy")]
    pub other_therapy: Option<Vec<ClinicalUseDefinitionContraindicationOtherTherapy>>,
}

/// Information about use of the product in relation to other therapies described as part of the contraindication
///
/// Information about the use of the medicinal product in relation to other
/// therapies described as part of the contraindication.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct ClinicalUseDefinitionContraindicationOtherTherapy {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The type of relationship between the product indication/contraindication and another therapy
    ///
    /// The type of relationship between the medicinal product indication or
    /// contraindication and another therapy.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: Classification of relationship between a therapy and a contraindication or an indication.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/therapy-relationship-type
    #[fhir_serde(rename = "relationshipType")]
    pub relationship_type: CodeableConcept,
    /// Reference to a specific medication as part of an indication or contraindication
    ///
    /// Reference to a specific medication (active substance, medicinal product or
    /// class of products) as part of an indication or contraindication.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A therapy.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/therapy
    pub therapy: CodeableReference,
}

/// Choice of types for the duration\[x\] field in ClinicalUseDefinitionIndication
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "duration")]
pub enum ClinicalUseDefinitionIndicationDuration {
    /// Variant accepting the Range type.
    #[fhir_serde(rename = "durationRange")]
    Range(Range),
    /// Variant accepting the String type.
    #[fhir_serde(rename = "durationString")]
    String(String),
}

/// Specifics for when this is an indication
///
/// Specifics for when this is an indication.
///
/// ## Cardinality: Optional (0..1)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(choice_elements = "duration")]
pub struct ClinicalUseDefinitionIndication {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The situation that is being documented as an indicaton for this item
    ///
    /// The situation that is being documented as an indicaton for this item.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A symptom, disease or procedure.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-symptom-procedure
    #[fhir_serde(rename = "diseaseSymptomProcedure")]
    pub disease_symptom_procedure: Option<CodeableReference>,
    /// The status of the disease or symptom for the indication
    ///
    /// The status of the disease or symptom for the indication, for example
    /// "chronic" or "metastatic".
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: The status of a disease or symptom.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-status
    #[fhir_serde(rename = "diseaseStatus")]
    pub disease_status: Option<CodeableReference>,
    /// A comorbidity or coinfection as part of the indication
    ///
    /// A comorbidity (concurrent condition) or coinfection as part of the
    /// indication.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A symptom, disease or procedure.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/disease-symptom-procedure
    pub comorbidity: Option<Vec<CodeableReference>>,
    /// The intended effect, aim or strategy to be achieved
    ///
    /// The intended effect, aim or strategy to be achieved.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: The overall intended use of a product.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/product-intended-use
    #[fhir_serde(rename = "intendedEffect")]
    pub intended_effect: Option<CodeableReference>,
    /// Timing or duration information
    ///
    /// Timing or duration information, that may be associated with use with the
    /// indicated condition e.g. Adult patients suffering from myocardial infarction
    /// (from a few days until less than 35 days), ischaemic stroke (from 7 days
    /// until less than 6 months).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(flatten)]
    pub duration: Option<ClinicalUseDefinitionIndicationDuration>,
    /// An unwanted side effect or negative outcome of the subject of this resource when being used for this indication
    ///
    /// An unwanted side effect or negative outcome that may happen if you use the
    /// drug (or other subject of this resource) for this indication.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "undesirableEffect")]
    pub undesirable_effect: Option<Vec<Reference>>,
    /// The use of the medicinal product in relation to other therapies described as part of the indication
    ///
    /// Information about the use of the medicinal product in relation to other
    /// therapies described as part of the indication.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "otherTherapy")]
    pub other_therapy: Option<Vec<ClinicalUseDefinitionContraindicationOtherTherapy>>,
}

/// Specifics for when this is an interaction
///
/// Specifics for when this is an interaction.
///
/// ## Cardinality: Optional (0..1)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct ClinicalUseDefinitionInteraction {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The specific medication, food, substance or laboratory test that interacts
    ///
    /// The specific medication, food, substance or laboratory test that interacts.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
    ///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
    pub interactant: Option<Vec<ClinicalUseDefinitionInteractionInteractant>>,
    /// The type of the interaction e.g. drug-drug interaction, drug-lab test interaction
    ///
    /// The type of the interaction e.g. drug-drug interaction, drug-food
    /// interaction, drug-lab test interaction.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A categorisation for an interaction between two substances.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/interaction-type
    #[fhir_serde(rename = "type")]
    pub r#type: Option<CodeableConcept>,
    /// The effect of the interaction, for example "reduced gastric absorption of primary medication"
    ///
    /// The effect of the interaction, for example "reduced gastric absorption of
    /// primary medication".
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A interaction effect of clinical use of a medication or other substance.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/interaction-effect
    pub effect: Option<CodeableReference>,
    /// The incidence of the interaction, e.g. theoretical, observed
    ///
    /// The incidence of the interaction, e.g. theoretical, observed.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A categorisation for incidence of occurence of an interaction.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/interaction-incidence
    pub incidence: Option<CodeableConcept>,
    /// Actions for managing the interaction
    ///
    /// Actions for managing the interaction.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A type of management for an interaction of a medication or other substance.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/interaction-management
    pub management: Option<Vec<CodeableConcept>>,
}

/// Choice of types for the item\[x\] field in ClinicalUseDefinitionInteractionInteractant
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "item")]
pub enum ClinicalUseDefinitionInteractionInteractantItem {
    /// Variant accepting the Reference type.
    #[fhir_serde(rename = "itemReference")]
    Reference(Reference),
    /// Variant accepting the CodeableConcept type.
    #[fhir_serde(rename = "itemCodeableConcept")]
    CodeableConcept(CodeableConcept),
}

/// The specific medication, food, substance or laboratory test that interacts
///
/// The specific medication, food, substance or laboratory test that interacts.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(choice_elements = "item")]
pub struct ClinicalUseDefinitionInteractionInteractant {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The specific medication, food or laboratory test that interacts
    ///
    /// The specific medication, food or laboratory test that interacts.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: An interactant - a substance that may have an clinically significant effect on another.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/interactant
    #[fhir_serde(flatten)]
    pub item: Option<ClinicalUseDefinitionInteractionInteractantItem>,
}

/// A possible negative outcome from the use of this treatment
///
/// Describe the possible undesirable effects (negative outcomes) from the use of
/// the medicinal product as treatment.
///
/// ## Cardinality: Optional (0..1)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct ClinicalUseDefinitionUndesirableEffect {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The situation in which the undesirable effect may manifest
    ///
    /// The situation in which the undesirable effect may manifest.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: An undesirable effect of clinical use.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/undesirable-effect-symptom
    #[fhir_serde(rename = "symptomConditionEffect")]
    pub symptom_condition_effect: Option<CodeableReference>,
    /// High level classification of the effect
    ///
    /// High level classification of the effect.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A categorisation for an undesirable effect.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/undesirable-effect-classification
    pub classification: Option<CodeableConcept>,
    /// How often the effect is seen
    ///
    /// How often the effect is seen.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: A categorisation for a frequency of occurence of an undesirable effect.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/undesirable-effect-frequency
    #[fhir_serde(rename = "frequencyOfOccurrence")]
    pub frequency_of_occurrence: Option<CodeableConcept>,
}

/// Critical environmental, health or physical risks or hazards. For example 'Do not operate heavy machinery', 'May cause drowsiness'
///
/// A critical piece of information about environmental, health or physical risks
/// or hazards that serve as caution to the user. For example 'Do not operate
/// heavy machinery', 'May cause drowsiness', or 'Get medical advice/attention if
/// you feel unwell'.
///
/// ## Cardinality: Optional (0..1)
///
/// ## Special Semantics
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children unless an empty Parameters resource (error)
///   Expression: `hasValue() or (children().count() > id.count()) or $this is Parameters`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct ClinicalUseDefinitionWarning {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and manageable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and manageable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **ext-1**: Must have either extensions or value[x], not both (error)
    ///   Expression: `extension.exists() != value.exists()`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// A textual definition of this warning, with formatting
    ///
    /// A textual definition of this warning, with formatting.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub description: Option<Markdown>,
    /// A coded or unformatted textual definition of this warning
    ///
    /// A coded or unformatted textual definition of this warning.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: example
    /// - **Description**: Classification of warning type.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/warning-type
    pub code: Option<CodeableConcept>,
}
