// AUTO-GENERATED by atrius-fhir-generator (R6 Patient)
use crate::r6::*;

/// Choice of types for the deceased\[x\] field in Patient
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "deceased")]
pub enum PatientDeceased {
    /// Variant accepting the Boolean type.
    #[fhir_serde(rename = "deceasedBoolean")]
    Boolean(Boolean),
    /// Variant accepting the DateTime type.
    #[fhir_serde(rename = "deceasedDateTime")]
    DateTime(DateTime),
}

/// Choice of types for the multipleBirth\[x\] field in Patient
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath)]
#[fhir_choice_element(base_name = "multipleBirth")]
pub enum PatientMultipleBirth {
    /// Variant accepting the Boolean type.
    #[fhir_serde(rename = "multipleBirthBoolean")]
    Boolean(Boolean),
    /// Variant accepting the Integer type.
    #[fhir_serde(rename = "multipleBirthInteger")]
    Integer(Integer),
}

/// FHIR Patient type
///
/// Demographics and other administrative information about an individual or
/// animal that is the subject of potential, past, current, or future
/// health-related care, services, or processes.
///
/// ## Purpose
/// Tracking patient is the center of the healthcare process.
///
/// ## Type: Resource type
/// Base type: http://hl7.org/fhir/StructureDefinition/DomainResource
///
/// ## Status: active
/// FHIR Version: 6.0.0-ballot3
///
/// See: [Patient](http://hl7.org/fhir/StructureDefinition/Patient)
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
#[fhir_resource(
    choice_elements = "deceased,multipleBirth",
    summary_fields = "id,meta,implicit_rules,modifier_extension,identifier,active,name,telecom,gender,birth_date,deceased,address,managing_organization,link"
)]
pub struct Patient {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    ///
    /// ## Implementation Notes
    /// Within the context of the FHIR RESTful interactions, the resource has an id
    /// except for cases like the create and conditional update. Otherwise, the use
    /// of the resouce id depends on the given use case.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    pub id: Option<String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub meta: Option<Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content. Often,
    /// this is a reference to an implementation guide that defines the special rules
    /// along with other profiles etc. For DomainResources, if more than one
    /// implicitRules policy applies, additional policies may be conveyed using the
    /// [additionalImplicitRules](https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-additionalImplicitRules.html)
    /// extension.
    ///
    /// ## Implementation Notes
    /// Asserting this rule set restricts the content to be only understood by a
    /// limited set of trading partners. This inherently limits the usefulness of the
    /// data in the long term. However, the existing health eco-system is highly
    /// fractured, and not yet ready to define, collect, and exchange data in a
    /// generally computable sense. Wherever possible, implementers and/or
    /// specification writers should avoid using this element. Often, when used, the
    /// URL is a reference to an implementation guide that defines these special
    /// rules as part of its narrative along with other profiles, value sets, etc.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because the implicit rules may provide additional knowledge about the resource that modifies its meaning or interpretation
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "implicitRules")]
    pub implicit_rules: Option<Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    ///
    /// ## Implementation Notes
    /// Language is provided to support indexing and accessibility (typically,
    /// services such as text to speech use the language tag). The html language tag
    /// in the narrative applies to the narrative. The language tag on the resource
    /// may be used to specify the language of other presentations generated from the
    /// data in the resource. Not all the content has to be in the base language. The
    /// Resource.language should not be assumed to apply to the narrative
    /// automatically. If a language is specified, it should it also be specified on
    /// the div element in the html (see rules in HTML5 for information about the
    /// relationship between xml:lang and the html lang attribute).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: IETF language tag for a human language
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/all-languages|6.0.0-ballot3
    pub language: Option<Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can be
    /// used to represent the content of the resource to a human. The narrative need
    /// not encode all the structured data, but is required to contain sufficient
    /// detail to make it "clinically safe" for a human to just read the narrative.
    /// Resource definitions may define what content should be represented in the
    /// narrative to ensure clinical safety.
    ///
    /// ## Implementation Notes
    /// Contained resources do not have a narrative. Resources that are not contained
    /// SHOULD have a narrative. In some cases, a resource may only have text with
    /// little or no additional discrete data (as long as all minOccurs=1 elements
    /// are satisfied). This may be necessary for data from legacy systems where
    /// information is captured as a "text blob" or where text is additionally
    /// entered raw or narrated and encoded information is added later.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// narrative, html, xhtml, display
    ///
    /// ## Conditions
    /// Used when: dom-6
    pub text: Option<Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, nor can they
    /// have their own independent transaction scope. This is allowed to be a
    /// Parameters resource if and only if it is referenced by a resource that
    /// provides context/meaning.
    ///
    /// ## Implementation Notes
    /// This should never be done when the content can be identified properly, as
    /// once identification is lost, it is extremely difficult (and context
    /// dependent) to restore it again. Contained resources may have profiles and
    /// tags in their meta elements, but SHALL NOT have security labels. Contained
    /// resources may be a resource type defined in the FHIR specification, or an
    /// [additional resource](resource.html#additional).
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Aliases
    /// inline resources, anonymous resources, contained resources
    ///
    /// ## Conditions
    /// Used when: dom-2, dom-4, dom-3, dom-5
    pub contained: Option<Vec<Resource>>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the resource and that modifies the understanding of the element
    /// that contains it and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer is allowed to define an extension, there is a set of requirements
    /// that SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the resource that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// An identifier for this patient
    ///
    /// An identifier for this patient.
    ///
    /// ## Requirements
    /// Patients are almost always assigned specific numerical identifiers.
    ///
    /// ## Implementation Notes
    /// Systems MAY use identifier for user identities (using the type='USER'). Refer
    /// to the [Security and Privacy](administration-module.html#secpriv) section for
    /// additional guidance on representing user identities.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub identifier: Option<Vec<Identifier>>,
    /// Whether this patient's record is in active use
    ///
    /// Whether this patient record is in active use.
    /// Many systems use this property to mark as non-current patients, such as those
    /// that have not been seen for a period of time based on an organization's
    /// business rules.
    ///
    /// It is often used to filter patient lists to exclude inactive patients
    ///
    /// Deceased patients may also be marked as inactive for the same reasons, but
    /// may be active for some time after death.
    ///
    /// ## Requirements
    /// Need to be able to mark a patient record as not to be used because it was
    /// created in error.
    ///
    /// ## Implementation Notes
    /// If a record is inactive, and linked to an active record, then future
    /// patient/record updates should occur on the other patient.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labelled as a modifier because it is a status element that can indicate that a record should not be treated as valid
    /// - Included in summary
    /// - When missing: This resource is generally assumed to be active if no value is provided for the active element
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub active: Option<Boolean>,
    /// A name associated with the patient
    ///
    /// A name associated with the individual.
    ///
    /// ## Requirements
    /// Need to be able to track the patient by multiple names. Examples are your
    /// official name and a partner name.
    ///
    /// ## Implementation Notes
    /// A patient may have multiple names with different uses or applicable periods.
    /// For animals, the name is a "HumanName" in the sense that is assigned and used
    /// by humans and has the same patterns. Animal names may be communicated as
    /// given names, and optionally may include a family name.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub name: Option<Vec<HumanName>>,
    /// A contact detail for the individual
    ///
    /// A contact detail (e.g. a telephone number or an email address) by which the
    /// individual may be contacted.
    ///
    /// ## Requirements
    /// People have (primary) ways to contact them in some way such as phone, email.
    ///
    /// ## Implementation Notes
    /// A Patient may have multiple ways to be contacted with different uses or
    /// applicable periods. May need to have options for contacting the person
    /// urgently and also to help with identification. The address might not go
    /// directly to the individual, but may reach another party that is able to proxy
    /// for the patient (i.e. home phone, or pet owner's phone).
    ///
    /// DO NOT use .telecom properties to represent user identities. Refer to the
    /// [Security and Privacy](administration-module.html#secpriv) section for
    /// additional guidance on representing user identities.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub telecom: Option<Vec<ContactPoint>>,
    /// male | female | other | unknown
    ///
    /// Administrative Gender - the gender that the patient is considered to have for
    /// administration and record keeping purposes.
    ///
    /// See the [Patient Gender and Sex section](patient.html#gender) for additional
    /// information about communicating patient gender and sex.
    ///
    /// ## Requirements
    /// Needed for identification of the individual, in combination with (at least)
    /// name and birth date.
    ///
    /// ## Implementation Notes
    /// The gender might not match the biological sex as determined by genetics or
    /// the individual's preferred identification. Note that for both humans and
    /// particularly animals, there are other legitimate possibilities than male and
    /// female, though the vast majority of systems and contexts only support male
    /// and female. Systems providing decision support or enforcing business rules
    /// should ideally do this on the basis of Observations dealing with the specific
    /// sex or gender aspect of interest (anatomical, chromosomal, social, etc.)
    /// However, because these observations are infrequently recorded, defaulting to
    /// the administrative gender is common practice. Where such defaulting occurs,
    /// rule enforcement should allow for the variation between administrative and
    /// biological, chromosomal and other gender aspects. For example, an alert about
    /// a hysterectomy on a male should be handled as a warning or overridable error,
    /// not a "hard" error.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: The gender of a person used for administrative purposes.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/administrative-gender|6.0.0-ballot3
    pub gender: Option<Code>,
    /// The date of birth for the individual
    ///
    /// The date of birth for the individual.
    ///
    /// ## Requirements
    /// Age of the individual drives many clinical processes.
    ///
    /// ## Implementation Notes
    /// Partial dates are allowed if the specific date of birth is unknown. There is
    /// a standard extension "patient-birthTime" available that should be used where
    /// Time is required (such as in maternity/infant care systems).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "birthDate")]
    pub birth_date: Option<Date>,
    /// Indicates if/when the individual is deceased
    ///
    /// Indicates the date when the individual died, or, if the date is not known or
    /// cannot be estimated, a flag indicating the patient is known to be deceased.
    ///
    /// ## Requirements
    /// The fact that a patient is deceased influences the clinical process. Also, in
    /// human communication and relation management it is necessary to know whether
    /// the person is alive.
    ///
    /// ## Implementation Notes
    /// If there's no value in the instance, it means there is no statement on
    /// whether or not the individual is deceased. Most systems will interpret the
    /// absence of a value as a sign of the person being alive.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because once a patient is marked as deceased, the actions that are appropriate to perform on the patient may be significantly different.
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(flatten)]
    pub deceased: Option<PatientDeceased>,
    /// An address for the individual
    ///
    /// An address for the individual.
    ///
    /// ## Requirements
    /// May need to keep track of patient addresses for contacting, billing or
    /// reporting requirements and also to help with identification.
    ///
    /// ## Implementation Notes
    /// Patient may have multiple addresses with different uses or applicable
    /// periods.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub address: Option<Vec<Address>>,
    /// Marital (civil) status of a patient
    ///
    /// This field contains a patient's most recent marital (civil) status.
    ///
    /// ## Requirements
    /// Most, if not all systems capture it.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: extensible
    /// - **Description**: The domestic partnership status of a person.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/marital-status
    #[fhir_serde(rename = "maritalStatus")]
    pub marital_status: Option<CodeableConcept>,
    /// Whether patient is part of a multiple birth
    ///
    /// Indicates whether the patient is part of a multiple (boolean) or indicates
    /// the actual birth order (integer). This count is relative to the total of live
    /// births and fetal losses, which MAY be tracked in the
    /// `patient-multipleBirthTotal` extension.
    ///
    /// The boolean option for this property can also be used to track that there are
    /// known to be multiple fetuses prior to birth.
    ///
    /// ## Requirements
    /// For disambiguation of multiple-birth children, especially relevant where the
    /// care provider doesn't meet the patient, such as labs.
    ///
    /// ## Implementation Notes
    /// Where the valueInteger is provided, the number is the birth number in the
    /// sequence.
    ///
    /// E.g. The middle birth in triplets would be valueInteger=2 and the third born
    /// would have valueInteger=3.
    /// If a boolean value was provided for this triplets example, then all 3 patient
    /// records would have valueBoolean=true (the ordering is not indicated).
    ///
    /// `valueBoolean` can be used to track fetuses. `valueInteger` should only be
    /// used after live birth.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(flatten)]
    pub multiple_birth: Option<PatientMultipleBirth>,
    /// Image of the patient
    ///
    /// Image of the patient.
    ///
    /// ## Requirements
    /// Many EHR systems have the capability to capture an image of the patient. Fits
    /// with newer social media usage too.
    ///
    /// ## Implementation Notes
    /// Guidelines:
    /// * Use id photos, not clinical photos.
    /// * Limit dimensions to thumbnail.
    /// * Keep byte count low to ease resource updates.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub photo: Option<Vec<Attachment>>,
    /// A contact party (e.g. guardian, partner, friend) for the patient
    ///
    /// A contact party (e.g. guardian, partner, friend) for the patient.
    ///
    /// ## Requirements
    /// Need to track people you can contact about the patient.
    ///
    /// ## Implementation Notes
    /// Contact covers all kinds of contact parties: family members, business
    /// contacts, guardians, caregivers. Not applicable to register pedigree and
    /// family ties beyond use of having contact.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children or both (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    /// - **pat-1**: SHALL at least contain a contact's details or a reference to an organization (error)
    ///   Expression: `name.exists() or telecom.exists() or address.exists() or organization.exists()`
    pub contact: Option<Vec<PatientContact>>,
    /// A language which may be used to communicate with the patient about his or her health
    ///
    /// A language which may be used to communicate with the patient about his or her
    /// health.
    ///
    /// ## Requirements
    /// If a patient does not speak the local language, interpreters may be required,
    /// so languages spoken and proficiency are important things to keep track of
    /// both for patient and other persons of interest.
    ///
    /// ## Implementation Notes
    /// If no language is specified, this *implies* that the default local language
    /// is spoken. If you need to convey proficiency for multiple modes, then you
    /// need multiple Patient.Communication associations. For animals, language is
    /// not a relevant field, and should be absent from the instance. If the Patient
    /// does not speak the default local language, then the Interpreter Required
    /// Standard can be used to explicitly declare that an interpreter is required.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children or both (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub communication: Option<Vec<PatientCommunication>>,
    /// Patient's nominated primary care provider
    ///
    /// Patient's nominated care provider.
    ///
    /// ## Implementation Notes
    /// This may be the primary care provider (in a GP context), or it may be a
    /// patient nominated care manager in a community/disability setting, or even
    /// organization that will provide people to perform the care provider roles. It
    /// is not to be used to record Care Teams, these should be in a CareTeam
    /// resource that may be linked to the CarePlan or EpisodeOfCare resources.
    /// Multiple GPs may be recorded against the patient for various reasons, such as
    /// a student that has his home GP listed along with the GP at university during
    /// the school semesters, or a "fly-in/fly-out" worker that has the onsite GP
    /// also included with his home GP to remain aware of medical issues.
    ///
    /// Jurisdictions may decide that they can profile this down to 1 if desired, or
    /// 1 per type.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// careProvider
    #[fhir_serde(rename = "generalPractitioner")]
    pub general_practitioner: Option<Vec<Reference>>,
    /// Organization that is the custodian of the patient record
    ///
    /// Organization that is the custodian of the patient record.
    ///
    /// ## Requirements
    /// Need to know who recognizes this patient record, manages and updates it.
    ///
    /// ## Implementation Notes
    /// There is only one managing organization for a specific patient record. Other
    /// organizations will have their own Patient record, and may use the Link
    /// property to join the records together (or a Person resource which can include
    /// confidence ratings for the association).
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "managingOrganization")]
    pub managing_organization: Option<Reference>,
    /// Link to a Patient or RelatedPerson resource that concerns the same actual individual
    ///
    /// Link to a Patient or RelatedPerson resource that concerns the same actual
    /// individual.
    ///
    /// ## Requirements
    /// There are multiple use cases:   
    ///
    /// * Duplicate patient records due to the clerical errors associated with the
    ///   difficulties of identifying humans consistently, and
    /// * Distribution of patient information across multiple servers.
    ///
    /// ## Implementation Notes
    /// There is no assumption that linked patient records have mutual links.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - This element is labeled as a modifier because it might not be the main Patient resource, and the referenced patient should be used instead of this Patient record. This is when the link.type value is 'replaced-by'
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children or both (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub link: Option<Vec<PatientLink>>,
}

/// A language which may be used to communicate with the patient about his or her health
///
/// A language which may be used to communicate with the patient about his or her
/// health.
///
/// ## Requirements
/// If a patient does not speak the local language, interpreters may be required,
/// so languages spoken and proficiency are important things to keep track of
/// both for patient and other persons of interest.
///
/// ## Implementation Notes
/// If no language is specified, this *implies* that the default local language
/// is spoken. If you need to convey proficiency for multiple modes, then you
/// need multiple Patient.Communication associations. For animals, language is
/// not a relevant field, and should be absent from the instance. If the Patient
/// does not speak the default local language, then the Interpreter Required
/// Standard can be used to explicitly declare that an interpreter is required.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children or both (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct PatientCommunication {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The language which can be used to communicate with the patient about his or her health
    ///
    /// The language which may be used to communicate with the individual.
    ///
    /// ## Requirements
    /// Most systems in multilingual countries will want to convey language. Not all
    /// systems actually need the regional dialect.
    ///
    /// ## Implementation Notes
    /// The language is commonly represented using the ISO-639-1 alpha code in lower
    /// case for the language, optionally followed by a hyphen and the ISO-3166-1
    /// alpha code for the region in upper case. For example, "en" for English, or
    /// "en-US" for American English versus "en-AU" for Australian English, sgn-US
    /// for American Sign Language, sgn-NL for Dutch Sign Language, etc.
    ///
    /// Not all systems actually code this but instead have it as free text. Hence
    /// CodeableConcept instead of code as the data type.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: IETF language tag for a human language
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/all-languages|6.0.0-ballot3
    pub language: CodeableConcept,
    /// Language preference indicator
    ///
    /// Indicates whether or not the patient prefers this language (over other
    /// languages he masters up a certain level).
    ///
    /// ## Requirements
    /// People that master multiple languages up to certain level may prefer one or
    /// more, i.e. feel more confident in communicating in a particular language
    /// making other languages sort of a fall back method.
    ///
    /// ## Implementation Notes
    /// This language is specifically identified for communicating healthcare
    /// information.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub preferred: Option<Boolean>,
}

/// A contact party (e.g. guardian, partner, friend) for the patient
///
/// A contact party (e.g. guardian, partner, friend) for the patient.
///
/// ## Requirements
/// Need to track people you can contact about the patient.
///
/// ## Implementation Notes
/// Contact covers all kinds of contact parties: family members, business
/// contacts, guardians, caregivers. Not applicable to register pedigree and
/// family ties beyond use of having contact.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children or both (error)
///   Expression: `hasValue() or (children().count() > id.count())`
/// - **pat-1**: SHALL at least contain a contact's details or a reference to an organization (error)
///   Expression: `name.exists() or telecom.exists() or address.exists() or organization.exists()`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct PatientContact {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The kind of personal relationship
    ///
    /// The nature of the personal relationship between the patient and the contact
    /// person.
    ///
    /// ## Requirements
    /// Used to determine the nature of the personal relationship between the patient
    /// and the contact person.
    ///
    /// ## Implementation Notes
    /// This property is for personal relationships. Functional relationships would
    /// be represented in `Patient.contact.role`.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: The nature of the personal relationship between the patient and the contact person.
    /// - **ValueSet**: http://terminology.hl7.org/ValueSet/v3-PersonalRelationshipRoleType
    pub relationship: Option<Vec<CodeableConcept>>,
    /// The kind of functional role
    ///
    /// The nature of the functional role between the patient and the contact person.
    ///
    /// ## Requirements
    /// Used to determine which contact person is the most relevant to approach,
    /// depending on circumstances.
    ///
    /// ## Implementation Notes
    /// This property is for functional relationships. Personal relationships would
    /// be represented in `Patient.contact.relationship`.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: preferred
    /// - **Description**: The nature of the personal relationship between the patient and the contact person.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype
    pub role: Option<Vec<CodeableConcept>>,
    /// A name associated with the contact person
    ///
    /// A name associated with the contact person. Alternate/additional names for
    /// this contact can be found in the `additionalName` property.
    ///
    /// ## Requirements
    /// Contact persons need to be identified by name. Where multiple names are
    /// required, such as legal name and usual (Name to Use) name, also refer to the
    /// `additionalName` property.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: pat-1
    pub name: Option<HumanName>,
    /// Additional names for the contact person
    ///
    /// Additional names for the contact person.
    ///
    /// ## Implementation Notes
    /// **To maintain backward compatibility, `additionalName` was added as a way to
    /// express names beyond the single name that can be represented in
    /// `Patient.contact.name`.**
    ///  
    /// When looking for an name of a given type, implementers should inspect both
    /// `Patient.contact.name` and `Patient.contact.additionalName`, and treat those
    /// two properties as a single combined logical list of names.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "additionalName")]
    pub additional_name: Option<Vec<HumanName>>,
    /// A contact detail for the person
    ///
    /// A contact detail for the person, e.g. a telephone number or an email address.
    ///
    /// ## Requirements
    /// People have (primary) ways to contact them in some way such as phone, email.
    ///
    /// ## Implementation Notes
    /// Contact may have multiple ways to be contacted with different uses or
    /// applicable periods. May need to have options for contacting the person
    /// urgently, and also to help with identification.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: pat-1
    pub telecom: Option<Vec<ContactPoint>>,
    /// Address for the contact person
    ///
    /// Address for the contact person. Alternate/additional addresses for this
    /// contact can be found in the `additionalAddress` property.
    ///
    /// ## Requirements
    /// Need to keep track where the contact person can be contacted per postal mail
    /// or visited.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: pat-1
    pub address: Option<Address>,
    /// Additional addresses for the contact person
    ///
    /// Additional addresses for the contact person.
    ///
    /// ## Requirements
    /// Need to keep track where the contact person can be contacted per postal mail
    /// or visited.
    ///
    /// ## Implementation Notes
    /// **To maintain backward compatibility, `additionalAddress` was added as a way
    /// to express addresses beyond the single address that can be represented in
    /// Patient.contact.address.**
    ///  
    /// When looking for an address of a given type, implementers should inspect both
    /// `Patient.contact.address` and `Patient.contact.additionalAddress`, and treat
    /// those two properties as a single combined logical list of addresses.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    #[fhir_serde(rename = "additionalAddress")]
    pub additional_address: Option<Vec<Address>>,
    /// male | female | other | unknown
    ///
    /// Administrative Gender - the gender that the contact person is considered to
    /// have for administration and record keeping purposes.
    ///
    /// ## Requirements
    /// Needed to address the person correctly.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: The gender of a person used for administrative purposes.
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/administrative-gender|6.0.0-ballot3
    pub gender: Option<Code>,
    /// Organization that is associated with the contact
    ///
    /// Organization on behalf of which the contact is acting or for which the
    /// contact is working.
    ///
    /// ## Requirements
    /// For guardians or business related contacts, the organization is relevant.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Conditions
    /// Used when: pat-1
    pub organization: Option<Reference>,
    /// The period during which this contact person or organization is valid to be contacted relating to this patient
    ///
    /// The period during which this contact person or organization is valid to be
    /// contacted relating to this patient.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub period: Option<Period>,
}

/// Link to a Patient or RelatedPerson resource that concerns the same actual individual
///
/// Link to a Patient or RelatedPerson resource that concerns the same actual
/// individual.
///
/// ## Requirements
/// There are multiple use cases:   
///
/// * Duplicate patient records due to the clerical errors associated with the
///   difficulties of identifying humans consistently, and
/// * Distribution of patient information across multiple servers.
///
/// ## Implementation Notes
/// There is no assumption that linked patient records have mutual links.
///
/// ## Cardinality: Optional, Multiple (0..*)
///
/// ## Special Semantics
/// - Modifier element - This element is labeled as a modifier because it might not be the main Patient resource, and the referenced patient should be used instead of this Patient record. This is when the link.type value is 'replaced-by'
/// - Included in summary
///
/// ## Constraints
/// - **ele-1**: All FHIR elements must have a @value or children or both (error)
///   Expression: `hasValue() or (children().count() > id.count())`
#[derive(Debug, Clone, PartialEq, FhirSerde, FhirPath, Default)]
pub struct PatientLink {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    ///
    /// ## Cardinality: Optional (0..1)
    ///
    /// ## Conditions
    /// Used when: ele-1
    pub id: Option<String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element. To make the use of extensions safe and managable,
    /// there is a strict set of governance applied to the definition and use of
    /// extensions. Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content
    pub extension: Option<Vec<Extension>>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the basic
    /// definition of the element and that modifies the understanding of the element
    /// in which it is contained and/or the understanding of the containing element's
    /// descendants. Usually modifier elements provide negation or qualification. To
    /// make the use of extensions safe and managable, there is a strict set of
    /// governance applied to the definition and use of extensions. Though any
    /// implementer can define an extension, there is a set of requirements that
    /// SHALL be met as part of the definition of the extension. Applications
    /// processing a resource are required to check for modifier extensions.
    ///
    /// Modifier extensions SHALL NOT change the meaning of any elements on Resource
    /// or DomainResource (including cannot change the meaning of modifierExtension
    /// itself).
    ///
    /// ## Requirements
    /// Modifier extensions allow for extensions that *cannot* be safely ignored to
    /// be clearly distinguished from the vast majority of extensions which can be
    /// safely ignored. This promotes interoperability by eliminating the need for
    /// implementers to prohibit the presence of extensions. For further information,
    /// see the [definition of modifier
    /// extensions](extensibility.html#modifierExtension).
    ///
    /// ## Implementation Notes
    /// There can be no stigma associated with the use of extensions by any
    /// application, project, or standard - regardless of the institution or
    /// jurisdiction that uses or defines the extensions. The use of extensions is
    /// what allows the FHIR specification to retain a core level of simplicity for
    /// everyone.
    ///
    /// ## Cardinality: Optional, Multiple (0..*)
    ///
    /// ## Special Semantics
    /// - Modifier element - Modifier extensions are expected to modify the meaning or interpretation of the element that contains them
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Aliases
    /// extensions, user content, modifiers
    #[fhir_serde(rename = "modifierExtension")]
    pub modifier_extension: Option<Vec<Extension>>,
    /// The other patient or related person resource that the link refers to
    ///
    /// Link to a Patient or RelatedPerson resource that concerns the same actual
    /// individual.
    ///
    /// ## Implementation Notes
    /// Referencing a RelatedPerson here removes the need to use a Person record to
    /// associate a Patient and RelatedPerson as the same individual.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    pub other: Reference,
    /// replaced-by | replaces | refer | seealso
    ///
    /// The type of link between this patient resource and another patient resource.
    ///
    /// ## Cardinality: Required (1..1)
    ///
    /// ## Special Semantics
    /// - Included in summary
    ///
    /// ## Constraints
    /// - **ele-1**: All FHIR elements must have a @value or children (error)
    ///   Expression: `hasValue() or (children().count() > id.count())`
    ///
    /// ## Binding
    /// - **Strength**: required
    /// - **Description**: The type of link between this patient resource and another Patient resource, or Patient/RelatedPerson when using the `seealso` code
    /// - **ValueSet**: http://hl7.org/fhir/ValueSet/link-type|6.0.0-ballot3
    #[fhir_serde(rename = "type")]
    pub r#type: Code,
}
